[lib]
name = "rust_miniscript_lib"
crate-type = ["cdylib"]

[package]
name = "rust_miniscript_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
miniscript = { git = "https://github.com/rust-bitcoin/rust-miniscript.git", rev = "f47cfd9b64b43e8181a8302fb82cc9921e462938" }
# miniscript = { version = "12.3.0", features = ["std", "compiler"] }
