/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the .csv file it was generated from. */
/* Original template can be found at tools/gen/impl_template */

#include <wire/onion_wiregen.h>
#include <assert.h>
#include <ccan/array_size/array_size.h>
#include <ccan/mem/mem.h>
#include <ccan/tal/str/str.h>
#include <common/utils.h>
#include <stdio.h>
#include <wire/onion_defs.h>

#ifndef SUPERVERBOSE
#define SUPERVERBOSE(...)
#endif


const char *onion_wire_name(int e)
{
	static char invalidbuf[sizeof("UNKNOWN ") + STR_MAX_CHARS(e)];

	switch ((enum onion_wire)e) {
	case WIRE_TEMPORARY_NODE_FAILURE: return "WIRE_TEMPORARY_NODE_FAILURE";
	case WIRE_PERMANENT_NODE_FAILURE: return "WIRE_PERMANENT_NODE_FAILURE";
	case WIRE_REQUIRED_NODE_FEATURE_MISSING: return "WIRE_REQUIRED_NODE_FEATURE_MISSING";
	case WIRE_INVALID_ONION_VERSION: return "WIRE_INVALID_ONION_VERSION";
	case WIRE_INVALID_ONION_HMAC: return "WIRE_INVALID_ONION_HMAC";
	case WIRE_INVALID_ONION_KEY: return "WIRE_INVALID_ONION_KEY";
	case WIRE_TEMPORARY_CHANNEL_FAILURE: return "WIRE_TEMPORARY_CHANNEL_FAILURE";
	case WIRE_PERMANENT_CHANNEL_FAILURE: return "WIRE_PERMANENT_CHANNEL_FAILURE";
	case WIRE_REQUIRED_CHANNEL_FEATURE_MISSING: return "WIRE_REQUIRED_CHANNEL_FEATURE_MISSING";
	case WIRE_UNKNOWN_NEXT_PEER: return "WIRE_UNKNOWN_NEXT_PEER";
	case WIRE_AMOUNT_BELOW_MINIMUM: return "WIRE_AMOUNT_BELOW_MINIMUM";
	case WIRE_FEE_INSUFFICIENT: return "WIRE_FEE_INSUFFICIENT";
	case WIRE_INCORRECT_CLTV_EXPIRY: return "WIRE_INCORRECT_CLTV_EXPIRY";
	case WIRE_EXPIRY_TOO_SOON: return "WIRE_EXPIRY_TOO_SOON";
	case WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS: return "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS";
	case WIRE_FINAL_INCORRECT_CLTV_EXPIRY: return "WIRE_FINAL_INCORRECT_CLTV_EXPIRY";
	case WIRE_FINAL_INCORRECT_HTLC_AMOUNT: return "WIRE_FINAL_INCORRECT_HTLC_AMOUNT";
	case WIRE_CHANNEL_DISABLED: return "WIRE_CHANNEL_DISABLED";
	case WIRE_EXPIRY_TOO_FAR: return "WIRE_EXPIRY_TOO_FAR";
	case WIRE_INVALID_ONION_PAYLOAD: return "WIRE_INVALID_ONION_PAYLOAD";
	case WIRE_MPP_TIMEOUT: return "WIRE_MPP_TIMEOUT";
	case WIRE_INVALID_ONION_BLINDING: return "WIRE_INVALID_ONION_BLINDING";
	}

	snprintf(invalidbuf, sizeof(invalidbuf), "UNKNOWN %i", e);
	return invalidbuf;
}

bool onion_wire_is_defined(u16 type)
{
	switch ((enum onion_wire)type) {
	case WIRE_TEMPORARY_NODE_FAILURE:;
	case WIRE_PERMANENT_NODE_FAILURE:;
	case WIRE_REQUIRED_NODE_FEATURE_MISSING:;
	case WIRE_INVALID_ONION_VERSION:;
	case WIRE_INVALID_ONION_HMAC:;
	case WIRE_INVALID_ONION_KEY:;
	case WIRE_TEMPORARY_CHANNEL_FAILURE:;
	case WIRE_PERMANENT_CHANNEL_FAILURE:;
	case WIRE_REQUIRED_CHANNEL_FEATURE_MISSING:;
	case WIRE_UNKNOWN_NEXT_PEER:;
	case WIRE_AMOUNT_BELOW_MINIMUM:;
	case WIRE_FEE_INSUFFICIENT:;
	case WIRE_INCORRECT_CLTV_EXPIRY:;
	case WIRE_EXPIRY_TOO_SOON:;
	case WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS:;
	case WIRE_FINAL_INCORRECT_CLTV_EXPIRY:;
	case WIRE_FINAL_INCORRECT_HTLC_AMOUNT:;
	case WIRE_CHANNEL_DISABLED:;
	case WIRE_EXPIRY_TOO_FAR:;
	case WIRE_INVALID_ONION_PAYLOAD:;
	case WIRE_MPP_TIMEOUT:;
	case WIRE_INVALID_ONION_BLINDING:;
	      return true;
	}
	return false;
}




/* SUBTYPE: BLINDED_PATH_HOP */
void towire_blinded_path_hop(u8 **p, const struct blinded_path_hop *blinded_path_hop)
{
	u16 enclen = tal_count(blinded_path_hop->encrypted_recipient_data);

	towire_pubkey(p, &blinded_path_hop->blinded_node_id);
	towire_u16(p, enclen);
	towire_u8_array(p, blinded_path_hop->encrypted_recipient_data, enclen);
}
struct blinded_path_hop *
fromwire_blinded_path_hop(const tal_t *ctx, const u8 **cursor, size_t *plen)
{
	struct blinded_path_hop *blinded_path_hop = tal(ctx, struct blinded_path_hop);
	u16 enclen;

 	fromwire_pubkey(cursor, plen, &blinded_path_hop->blinded_node_id);
 	enclen = fromwire_u16(cursor, plen);
 	blinded_path_hop->encrypted_recipient_data = tal_arr(blinded_path_hop, u8, enclen);
fromwire_u8_array(cursor, plen, blinded_path_hop->encrypted_recipient_data, enclen);

	return blinded_path_hop;
}

/* SUBTYPE: BLINDED_PATH */
void towire_blinded_path(u8 **p, const struct blinded_path *blinded_path)
{
	u8 num_hops = tal_count(blinded_path->path);

	towire_sciddir_or_pubkey(p, &blinded_path->first_node_id);
	towire_pubkey(p, &blinded_path->first_path_key);
	towire_u8(p, num_hops);
		for (size_t i = 0; i < num_hops; i++)
		towire_blinded_path_hop(p, blinded_path->path[i]);
}
struct blinded_path *
fromwire_blinded_path(const tal_t *ctx, const u8 **cursor, size_t *plen)
{
	struct blinded_path *blinded_path = tal(ctx, struct blinded_path);
	u8 num_hops;

 	fromwire_sciddir_or_pubkey(cursor, plen, &blinded_path->first_node_id);
 	fromwire_pubkey(cursor, plen, &blinded_path->first_path_key);
 	num_hops = fromwire_u8(cursor, plen);
 	blinded_path->path = num_hops ? tal_arr(blinded_path, struct blinded_path_hop *, 0) : NULL;
	for (size_t i = 0; i < num_hops; i++) {
		struct blinded_path_hop * tmp;
		tmp = fromwire_blinded_path_hop(blinded_path->path, cursor, plen);
		tal_arr_expand(&blinded_path->path, tmp);
	}

	return blinded_path;
}


struct tlv_payload *tlv_payload_new(const tal_t *ctx)
{
	/* Initialize everything to NULL. (Quiet, C pedants!) */
	struct tlv_payload *inst = talz(ctx, struct tlv_payload);

	/* Initialized the fields to an empty array. */
	inst->fields = tal_arr(inst, struct tlv_field, 0);
	return inst;
}

/* TLV_PAYLOAD MSG: amt_to_forward */
static u8 *towire_tlv_payload_amt_to_forward(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->amt_to_forward)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_tu64(&ptr, *r->amt_to_forward);
	return ptr;
}
static void fromwire_tlv_payload_amt_to_forward(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	    r->amt_to_forward = tal(r, u64);

*r->amt_to_forward = fromwire_tu64(cursor, plen);
}
/* TLV_PAYLOAD MSG: outgoing_cltv_value */
static u8 *towire_tlv_payload_outgoing_cltv_value(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->outgoing_cltv_value)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_tu32(&ptr, *r->outgoing_cltv_value);
	return ptr;
}
static void fromwire_tlv_payload_outgoing_cltv_value(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	    r->outgoing_cltv_value = tal(r, u32);

*r->outgoing_cltv_value = fromwire_tu32(cursor, plen);
}
/* TLV_PAYLOAD MSG: short_channel_id */
static u8 *towire_tlv_payload_short_channel_id(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->short_channel_id)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_short_channel_id(&ptr, *r->short_channel_id);
	return ptr;
}
static void fromwire_tlv_payload_short_channel_id(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	    r->short_channel_id = tal(r, struct short_channel_id);

*r->short_channel_id = fromwire_short_channel_id(cursor, plen);
}
/* TLV_PAYLOAD MSG: payment_data */
static u8 *towire_tlv_payload_payment_data(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->payment_data)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_secret(&ptr, &r->payment_data->payment_secret);

	towire_tu64(&ptr, r->payment_data->total_msat);
	return ptr;
}
static void fromwire_tlv_payload_payment_data(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	r->payment_data = tal(r, struct tlv_payload_payment_data);
	fromwire_secret(cursor, plen, &r->payment_data->payment_secret);
	r->payment_data->total_msat = fromwire_tu64(cursor, plen);
}
/* TLV_PAYLOAD MSG: encrypted_recipient_data */
static u8 *towire_tlv_payload_encrypted_recipient_data(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->encrypted_recipient_data)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->encrypted_recipient_data, tal_count(r->encrypted_recipient_data));
	return ptr;
}
static void fromwire_tlv_payload_encrypted_recipient_data(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	r->encrypted_recipient_data = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->encrypted_recipient_data, *plen);
}
/* TLV_PAYLOAD MSG: current_path_key */
static u8 *towire_tlv_payload_current_path_key(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->current_path_key)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_pubkey(&ptr, r->current_path_key);
	return ptr;
}
static void fromwire_tlv_payload_current_path_key(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	    r->current_path_key = tal(r, struct pubkey);

fromwire_pubkey(cursor, plen, &*r->current_path_key);
}
/* TLV_PAYLOAD MSG: payment_metadata */
static u8 *towire_tlv_payload_payment_metadata(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->payment_metadata)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->payment_metadata, tal_count(r->payment_metadata));
	return ptr;
}
static void fromwire_tlv_payload_payment_metadata(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	r->payment_metadata = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->payment_metadata, *plen);
}
/* TLV_PAYLOAD MSG: total_amount_msat */
static u8 *towire_tlv_payload_total_amount_msat(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_payload *r = vrecord;
	u8 *ptr;

	if (!r->total_amount_msat)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_tu64(&ptr, *r->total_amount_msat);
	return ptr;
}
static void fromwire_tlv_payload_total_amount_msat(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_payload *r = vrecord;

	    r->total_amount_msat = tal(r, u64);

*r->total_amount_msat = fromwire_tu64(cursor, plen);
}

const struct tlv_record_type tlvs_tlv_payload[] = {
	{ 2, towire_tlv_payload_amt_to_forward, fromwire_tlv_payload_amt_to_forward },
	{ 4, towire_tlv_payload_outgoing_cltv_value, fromwire_tlv_payload_outgoing_cltv_value },
	{ 6, towire_tlv_payload_short_channel_id, fromwire_tlv_payload_short_channel_id },
	{ 8, towire_tlv_payload_payment_data, fromwire_tlv_payload_payment_data },
	{ 10, towire_tlv_payload_encrypted_recipient_data, fromwire_tlv_payload_encrypted_recipient_data },
	{ 12, towire_tlv_payload_current_path_key, fromwire_tlv_payload_current_path_key },
	{ 16, towire_tlv_payload_payment_metadata, fromwire_tlv_payload_payment_metadata },
	{ 18, towire_tlv_payload_total_amount_msat, fromwire_tlv_payload_total_amount_msat },
};

void towire_tlv_payload(u8 **pptr, const struct tlv_payload *record)
{
	towire_tlv(pptr, tlvs_tlv_payload, 8, record);
}


struct tlv_payload *fromwire_tlv_payload(const tal_t *ctx, const u8 **cursor, size_t *max)
{
	struct tlv_payload *record = tlv_payload_new(ctx);
	if (!fromwire_tlv(cursor, max, tlvs_tlv_payload, 8, record, &record->fields, NULL, NULL, NULL))
		return tal_free(record);
	return record;
}

struct tlv_encrypted_data_tlv *tlv_encrypted_data_tlv_new(const tal_t *ctx)
{
	/* Initialize everything to NULL. (Quiet, C pedants!) */
	struct tlv_encrypted_data_tlv *inst = talz(ctx, struct tlv_encrypted_data_tlv);

	/* Initialized the fields to an empty array. */
	inst->fields = tal_arr(inst, struct tlv_field, 0);
	return inst;
}

/* TLV_ENCRYPTED_DATA_TLV MSG: padding */
static u8 *towire_tlv_encrypted_data_tlv_padding(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->padding)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->padding, tal_count(r->padding));
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_padding(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	r->padding = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->padding, *plen);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: short_channel_id */
static u8 *towire_tlv_encrypted_data_tlv_short_channel_id(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->short_channel_id)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_short_channel_id(&ptr, *r->short_channel_id);
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_short_channel_id(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	    r->short_channel_id = tal(r, struct short_channel_id);

*r->short_channel_id = fromwire_short_channel_id(cursor, plen);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: next_node_id */
static u8 *towire_tlv_encrypted_data_tlv_next_node_id(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->next_node_id)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_pubkey(&ptr, r->next_node_id);
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_next_node_id(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	    r->next_node_id = tal(r, struct pubkey);

fromwire_pubkey(cursor, plen, &*r->next_node_id);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: path_id */
static u8 *towire_tlv_encrypted_data_tlv_path_id(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->path_id)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->path_id, tal_count(r->path_id));
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_path_id(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	r->path_id = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->path_id, *plen);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: next_path_key_override */
static u8 *towire_tlv_encrypted_data_tlv_next_path_key_override(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->next_path_key_override)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_pubkey(&ptr, r->next_path_key_override);
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_next_path_key_override(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	    r->next_path_key_override = tal(r, struct pubkey);

fromwire_pubkey(cursor, plen, &*r->next_path_key_override);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: payment_relay */
static u8 *towire_tlv_encrypted_data_tlv_payment_relay(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->payment_relay)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u16(&ptr, r->payment_relay->cltv_expiry_delta);

	towire_u32(&ptr, r->payment_relay->fee_proportional_millionths);

	towire_tu32(&ptr, r->payment_relay->fee_base_msat);
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_payment_relay(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	r->payment_relay = tal(r, struct tlv_encrypted_data_tlv_payment_relay);
	r->payment_relay->cltv_expiry_delta = fromwire_u16(cursor, plen);
	r->payment_relay->fee_proportional_millionths = fromwire_u32(cursor, plen);
	r->payment_relay->fee_base_msat = fromwire_tu32(cursor, plen);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: payment_constraints */
static u8 *towire_tlv_encrypted_data_tlv_payment_constraints(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->payment_constraints)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u32(&ptr, r->payment_constraints->max_cltv_expiry);

	towire_tu64(&ptr, r->payment_constraints->htlc_minimum_msat);
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_payment_constraints(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	r->payment_constraints = tal(r, struct tlv_encrypted_data_tlv_payment_constraints);
	r->payment_constraints->max_cltv_expiry = fromwire_u32(cursor, plen);
	r->payment_constraints->htlc_minimum_msat = fromwire_tu64(cursor, plen);
}
/* TLV_ENCRYPTED_DATA_TLV MSG: allowed_features */
static u8 *towire_tlv_encrypted_data_tlv_allowed_features(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_encrypted_data_tlv *r = vrecord;
	u8 *ptr;

	if (!r->allowed_features)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->allowed_features, tal_count(r->allowed_features));
	return ptr;
}
static void fromwire_tlv_encrypted_data_tlv_allowed_features(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_encrypted_data_tlv *r = vrecord;

	r->allowed_features = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->allowed_features, *plen);
}

static const struct tlv_record_type tlvs_tlv_encrypted_data_tlv[] = {
	{ 1, towire_tlv_encrypted_data_tlv_padding, fromwire_tlv_encrypted_data_tlv_padding },
	{ 2, towire_tlv_encrypted_data_tlv_short_channel_id, fromwire_tlv_encrypted_data_tlv_short_channel_id },
	{ 4, towire_tlv_encrypted_data_tlv_next_node_id, fromwire_tlv_encrypted_data_tlv_next_node_id },
	{ 6, towire_tlv_encrypted_data_tlv_path_id, fromwire_tlv_encrypted_data_tlv_path_id },
	{ 8, towire_tlv_encrypted_data_tlv_next_path_key_override, fromwire_tlv_encrypted_data_tlv_next_path_key_override },
	{ 10, towire_tlv_encrypted_data_tlv_payment_relay, fromwire_tlv_encrypted_data_tlv_payment_relay },
	{ 12, towire_tlv_encrypted_data_tlv_payment_constraints, fromwire_tlv_encrypted_data_tlv_payment_constraints },
	{ 14, towire_tlv_encrypted_data_tlv_allowed_features, fromwire_tlv_encrypted_data_tlv_allowed_features },
};

void towire_tlv_encrypted_data_tlv(u8 **pptr, const struct tlv_encrypted_data_tlv *record)
{
	towire_tlv(pptr, tlvs_tlv_encrypted_data_tlv, 8, record);
}


struct tlv_encrypted_data_tlv *fromwire_tlv_encrypted_data_tlv(const tal_t *ctx, const u8 **cursor, size_t *max)
{
	struct tlv_encrypted_data_tlv *record = tlv_encrypted_data_tlv_new(ctx);
	if (!fromwire_tlv(cursor, max, tlvs_tlv_encrypted_data_tlv, 8, record, &record->fields, NULL, NULL, NULL))
		return tal_free(record);
	return record;
}

struct tlv_onionmsg_tlv *tlv_onionmsg_tlv_new(const tal_t *ctx)
{
	/* Initialize everything to NULL. (Quiet, C pedants!) */
	struct tlv_onionmsg_tlv *inst = talz(ctx, struct tlv_onionmsg_tlv);

	/* Initialized the fields to an empty array. */
	inst->fields = tal_arr(inst, struct tlv_field, 0);
	return inst;
}

/* TLV_ONIONMSG_TLV MSG: reply_path */
static u8 *towire_tlv_onionmsg_tlv_reply_path(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_onionmsg_tlv *r = vrecord;
	u8 *ptr;

	if (!r->reply_path)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_blinded_path(&ptr, r->reply_path);
	return ptr;
}
static void fromwire_tlv_onionmsg_tlv_reply_path(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_onionmsg_tlv *r = vrecord;

	r->reply_path = fromwire_blinded_path(r, cursor, plen);
}
/* TLV_ONIONMSG_TLV MSG: encrypted_recipient_data */
static u8 *towire_tlv_onionmsg_tlv_encrypted_recipient_data(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_onionmsg_tlv *r = vrecord;
	u8 *ptr;

	if (!r->encrypted_recipient_data)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->encrypted_recipient_data, tal_count(r->encrypted_recipient_data));
	return ptr;
}
static void fromwire_tlv_onionmsg_tlv_encrypted_recipient_data(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_onionmsg_tlv *r = vrecord;

	r->encrypted_recipient_data = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->encrypted_recipient_data, *plen);
}
/* TLV_ONIONMSG_TLV MSG: invoice_request */
static u8 *towire_tlv_onionmsg_tlv_invoice_request(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_onionmsg_tlv *r = vrecord;
	u8 *ptr;

	if (!r->invoice_request)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->invoice_request, tal_count(r->invoice_request));
	return ptr;
}
static void fromwire_tlv_onionmsg_tlv_invoice_request(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_onionmsg_tlv *r = vrecord;

	r->invoice_request = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->invoice_request, *plen);
}
/* TLV_ONIONMSG_TLV MSG: invoice */
static u8 *towire_tlv_onionmsg_tlv_invoice(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_onionmsg_tlv *r = vrecord;
	u8 *ptr;

	if (!r->invoice)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->invoice, tal_count(r->invoice));
	return ptr;
}
static void fromwire_tlv_onionmsg_tlv_invoice(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_onionmsg_tlv *r = vrecord;

	r->invoice = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->invoice, *plen);
}
/* TLV_ONIONMSG_TLV MSG: invoice_error */
static u8 *towire_tlv_onionmsg_tlv_invoice_error(const tal_t *ctx, const void *vrecord)
{
	const struct tlv_onionmsg_tlv *r = vrecord;
	u8 *ptr;

	if (!r->invoice_error)
		return NULL;


	ptr = tal_arr(ctx, u8, 0);

	towire_u8_array(&ptr, r->invoice_error, tal_count(r->invoice_error));
	return ptr;
}
static void fromwire_tlv_onionmsg_tlv_invoice_error(const u8 **cursor, size_t *plen, void *vrecord)
{
	struct tlv_onionmsg_tlv *r = vrecord;

	r->invoice_error = tal_arr(r, u8, *plen);
fromwire_u8_array(cursor, plen, r->invoice_error, *plen);
}

static const struct tlv_record_type tlvs_tlv_onionmsg_tlv[] = {
	{ 2, towire_tlv_onionmsg_tlv_reply_path, fromwire_tlv_onionmsg_tlv_reply_path },
	{ 4, towire_tlv_onionmsg_tlv_encrypted_recipient_data, fromwire_tlv_onionmsg_tlv_encrypted_recipient_data },
	{ 64, towire_tlv_onionmsg_tlv_invoice_request, fromwire_tlv_onionmsg_tlv_invoice_request },
	{ 66, towire_tlv_onionmsg_tlv_invoice, fromwire_tlv_onionmsg_tlv_invoice },
	{ 68, towire_tlv_onionmsg_tlv_invoice_error, fromwire_tlv_onionmsg_tlv_invoice_error },
};

void towire_tlv_onionmsg_tlv(u8 **pptr, const struct tlv_onionmsg_tlv *record)
{
	towire_tlv(pptr, tlvs_tlv_onionmsg_tlv, 5, record);
}


struct tlv_onionmsg_tlv *fromwire_tlv_onionmsg_tlv(const tal_t *ctx, const u8 **cursor, size_t *max)
{
	struct tlv_onionmsg_tlv *record = tlv_onionmsg_tlv_new(ctx);
	if (!fromwire_tlv(cursor, max, tlvs_tlv_onionmsg_tlv, 5, record, &record->fields, NULL, NULL, NULL))
		return tal_free(record);
	return record;
}

/* WIRE: TEMPORARY_NODE_FAILURE */
u8 *towire_temporary_node_failure(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_TEMPORARY_NODE_FAILURE);

	return memcheck(p, tal_count(p));
}
bool fromwire_temporary_node_failure(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_TEMPORARY_NODE_FAILURE)
		return false;
	return cursor != NULL;
}

/* WIRE: PERMANENT_NODE_FAILURE */
u8 *towire_permanent_node_failure(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_PERMANENT_NODE_FAILURE);

	return memcheck(p, tal_count(p));
}
bool fromwire_permanent_node_failure(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_PERMANENT_NODE_FAILURE)
		return false;
	return cursor != NULL;
}

/* WIRE: REQUIRED_NODE_FEATURE_MISSING */
u8 *towire_required_node_feature_missing(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_REQUIRED_NODE_FEATURE_MISSING);

	return memcheck(p, tal_count(p));
}
bool fromwire_required_node_feature_missing(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_REQUIRED_NODE_FEATURE_MISSING)
		return false;
	return cursor != NULL;
}

/* WIRE: INVALID_ONION_VERSION */
u8 *towire_invalid_onion_version(const tal_t *ctx, const struct sha256 *sha256_of_onion)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INVALID_ONION_VERSION);
	towire_sha256(&p, sha256_of_onion);

	return memcheck(p, tal_count(p));
}
bool fromwire_invalid_onion_version(const void *p, struct sha256 *sha256_of_onion)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INVALID_ONION_VERSION)
		return false;
 	fromwire_sha256(&cursor, &plen, sha256_of_onion);
	return cursor != NULL;
}

/* WIRE: INVALID_ONION_HMAC */
u8 *towire_invalid_onion_hmac(const tal_t *ctx, const struct sha256 *sha256_of_onion)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INVALID_ONION_HMAC);
	towire_sha256(&p, sha256_of_onion);

	return memcheck(p, tal_count(p));
}
bool fromwire_invalid_onion_hmac(const void *p, struct sha256 *sha256_of_onion)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INVALID_ONION_HMAC)
		return false;
 	fromwire_sha256(&cursor, &plen, sha256_of_onion);
	return cursor != NULL;
}

/* WIRE: INVALID_ONION_KEY */
u8 *towire_invalid_onion_key(const tal_t *ctx, const struct sha256 *sha256_of_onion)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INVALID_ONION_KEY);
	towire_sha256(&p, sha256_of_onion);

	return memcheck(p, tal_count(p));
}
bool fromwire_invalid_onion_key(const void *p, struct sha256 *sha256_of_onion)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INVALID_ONION_KEY)
		return false;
 	fromwire_sha256(&cursor, &plen, sha256_of_onion);
	return cursor != NULL;
}

/* WIRE: TEMPORARY_CHANNEL_FAILURE */
u8 *towire_temporary_channel_failure(const tal_t *ctx, const u8 *channel_update)
{
	u16 len = tal_count(channel_update);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_TEMPORARY_CHANNEL_FAILURE);
	towire_u16(&p, len);
	towire_u8_array(&p, channel_update, len);

	return memcheck(p, tal_count(p));
}
bool fromwire_temporary_channel_failure(const tal_t *ctx, const void *p, u8 **channel_update)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_TEMPORARY_CHANNEL_FAILURE)
		return false;
 	len = fromwire_u16(&cursor, &plen);
 	// 2nd case channel_update
	*channel_update = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *channel_update, len);
	return cursor != NULL;
}

/* WIRE: PERMANENT_CHANNEL_FAILURE */
u8 *towire_permanent_channel_failure(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_PERMANENT_CHANNEL_FAILURE);

	return memcheck(p, tal_count(p));
}
bool fromwire_permanent_channel_failure(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_PERMANENT_CHANNEL_FAILURE)
		return false;
	return cursor != NULL;
}

/* WIRE: REQUIRED_CHANNEL_FEATURE_MISSING */
u8 *towire_required_channel_feature_missing(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_REQUIRED_CHANNEL_FEATURE_MISSING);

	return memcheck(p, tal_count(p));
}
bool fromwire_required_channel_feature_missing(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_REQUIRED_CHANNEL_FEATURE_MISSING)
		return false;
	return cursor != NULL;
}

/* WIRE: UNKNOWN_NEXT_PEER */
u8 *towire_unknown_next_peer(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_UNKNOWN_NEXT_PEER);

	return memcheck(p, tal_count(p));
}
bool fromwire_unknown_next_peer(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_UNKNOWN_NEXT_PEER)
		return false;
	return cursor != NULL;
}

/* WIRE: AMOUNT_BELOW_MINIMUM */
u8 *towire_amount_below_minimum(const tal_t *ctx, struct amount_msat htlc_msat, const u8 *channel_update)
{
	u16 len = tal_count(channel_update);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_AMOUNT_BELOW_MINIMUM);
	towire_amount_msat(&p, htlc_msat);
	towire_u16(&p, len);
	towire_u8_array(&p, channel_update, len);

	return memcheck(p, tal_count(p));
}
bool fromwire_amount_below_minimum(const tal_t *ctx, const void *p, struct amount_msat *htlc_msat, u8 **channel_update)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_AMOUNT_BELOW_MINIMUM)
		return false;
 	*htlc_msat = fromwire_amount_msat(&cursor, &plen);
 	len = fromwire_u16(&cursor, &plen);
 	// 2nd case channel_update
	*channel_update = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *channel_update, len);
	return cursor != NULL;
}

/* WIRE: FEE_INSUFFICIENT */
u8 *towire_fee_insufficient(const tal_t *ctx, struct amount_msat htlc_msat, const u8 *channel_update)
{
	u16 len = tal_count(channel_update);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_FEE_INSUFFICIENT);
	towire_amount_msat(&p, htlc_msat);
	towire_u16(&p, len);
	towire_u8_array(&p, channel_update, len);

	return memcheck(p, tal_count(p));
}
bool fromwire_fee_insufficient(const tal_t *ctx, const void *p, struct amount_msat *htlc_msat, u8 **channel_update)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_FEE_INSUFFICIENT)
		return false;
 	*htlc_msat = fromwire_amount_msat(&cursor, &plen);
 	len = fromwire_u16(&cursor, &plen);
 	// 2nd case channel_update
	*channel_update = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *channel_update, len);
	return cursor != NULL;
}

/* WIRE: INCORRECT_CLTV_EXPIRY */
u8 *towire_incorrect_cltv_expiry(const tal_t *ctx, u32 cltv_expiry, const u8 *channel_update)
{
	u16 len = tal_count(channel_update);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INCORRECT_CLTV_EXPIRY);
	towire_u32(&p, cltv_expiry);
	towire_u16(&p, len);
	towire_u8_array(&p, channel_update, len);

	return memcheck(p, tal_count(p));
}
bool fromwire_incorrect_cltv_expiry(const tal_t *ctx, const void *p, u32 *cltv_expiry, u8 **channel_update)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INCORRECT_CLTV_EXPIRY)
		return false;
 	*cltv_expiry = fromwire_u32(&cursor, &plen);
 	len = fromwire_u16(&cursor, &plen);
 	// 2nd case channel_update
	*channel_update = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *channel_update, len);
	return cursor != NULL;
}

/* WIRE: EXPIRY_TOO_SOON */
u8 *towire_expiry_too_soon(const tal_t *ctx, const u8 *channel_update)
{
	u16 len = tal_count(channel_update);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_EXPIRY_TOO_SOON);
	towire_u16(&p, len);
	towire_u8_array(&p, channel_update, len);

	return memcheck(p, tal_count(p));
}
bool fromwire_expiry_too_soon(const tal_t *ctx, const void *p, u8 **channel_update)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_EXPIRY_TOO_SOON)
		return false;
 	len = fromwire_u16(&cursor, &plen);
 	// 2nd case channel_update
	*channel_update = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *channel_update, len);
	return cursor != NULL;
}

/* WIRE: INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS */
u8 *towire_incorrect_or_unknown_payment_details(const tal_t *ctx, struct amount_msat htlc_msat, u32 height)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS);
	towire_amount_msat(&p, htlc_msat);
	towire_u32(&p, height);

	return memcheck(p, tal_count(p));
}
bool fromwire_incorrect_or_unknown_payment_details(const void *p, struct amount_msat *htlc_msat, u32 *height)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS)
		return false;
 	*htlc_msat = fromwire_amount_msat(&cursor, &plen);
 	*height = fromwire_u32(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: FINAL_INCORRECT_CLTV_EXPIRY */
u8 *towire_final_incorrect_cltv_expiry(const tal_t *ctx, u32 cltv_expiry)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_FINAL_INCORRECT_CLTV_EXPIRY);
	towire_u32(&p, cltv_expiry);

	return memcheck(p, tal_count(p));
}
bool fromwire_final_incorrect_cltv_expiry(const void *p, u32 *cltv_expiry)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_FINAL_INCORRECT_CLTV_EXPIRY)
		return false;
 	*cltv_expiry = fromwire_u32(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: FINAL_INCORRECT_HTLC_AMOUNT */
u8 *towire_final_incorrect_htlc_amount(const tal_t *ctx, struct amount_msat incoming_htlc_amt)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_FINAL_INCORRECT_HTLC_AMOUNT);
	towire_amount_msat(&p, incoming_htlc_amt);

	return memcheck(p, tal_count(p));
}
bool fromwire_final_incorrect_htlc_amount(const void *p, struct amount_msat *incoming_htlc_amt)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_FINAL_INCORRECT_HTLC_AMOUNT)
		return false;
 	*incoming_htlc_amt = fromwire_amount_msat(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNEL_DISABLED */
u8 *towire_channel_disabled(const tal_t *ctx, u16 disabled_flags, const u8 *channel_update)
{
	u16 len = tal_count(channel_update);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNEL_DISABLED);
	towire_u16(&p, disabled_flags);
	towire_u16(&p, len);
	towire_u8_array(&p, channel_update, len);

	return memcheck(p, tal_count(p));
}
bool fromwire_channel_disabled(const tal_t *ctx, const void *p, u16 *disabled_flags, u8 **channel_update)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNEL_DISABLED)
		return false;
 	*disabled_flags = fromwire_u16(&cursor, &plen);
 	len = fromwire_u16(&cursor, &plen);
 	// 2nd case channel_update
	*channel_update = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *channel_update, len);
	return cursor != NULL;
}

/* WIRE: EXPIRY_TOO_FAR */
u8 *towire_expiry_too_far(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_EXPIRY_TOO_FAR);

	return memcheck(p, tal_count(p));
}
bool fromwire_expiry_too_far(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_EXPIRY_TOO_FAR)
		return false;
	return cursor != NULL;
}

/* WIRE: INVALID_ONION_PAYLOAD */
u8 *towire_invalid_onion_payload(const tal_t *ctx, bigsize type, u16 offset)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INVALID_ONION_PAYLOAD);
	towire_bigsize(&p, type);
	towire_u16(&p, offset);

	return memcheck(p, tal_count(p));
}
bool fromwire_invalid_onion_payload(const void *p, bigsize *type, u16 *offset)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INVALID_ONION_PAYLOAD)
		return false;
 	*type = fromwire_bigsize(&cursor, &plen);
 	*offset = fromwire_u16(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: MPP_TIMEOUT */
u8 *towire_mpp_timeout(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_MPP_TIMEOUT);

	return memcheck(p, tal_count(p));
}
bool fromwire_mpp_timeout(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_MPP_TIMEOUT)
		return false;
	return cursor != NULL;
}

/* WIRE: INVALID_ONION_BLINDING */
u8 *towire_invalid_onion_blinding(const tal_t *ctx, const struct sha256 *sha256_of_onion)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_INVALID_ONION_BLINDING);
	towire_sha256(&p, sha256_of_onion);

	return memcheck(p, tal_count(p));
}
bool fromwire_invalid_onion_blinding(const void *p, struct sha256 *sha256_of_onion)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_INVALID_ONION_BLINDING)
		return false;
 	fromwire_sha256(&cursor, &plen, sha256_of_onion);
	return cursor != NULL;
}
// SHA256STAMP:7b39a9caa823c012defee80602f30459d19111d6bfaac2fe36eab3ed50994596
