/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
/* Original template can be found at tools/gen/header_template */

#ifndef LIGHTNING_WIRE_PEER_WIREGEN_H
#define LIGHTNING_WIRE_PEER_WIREGEN_H
#include <ccan/tal/tal.h>
#include <wire/tlvstream.h>
#include <wire/wire.h>
#include <common/channel_id.h>
#include <bitcoin/tx.h>
#include <bitcoin/preimage.h>
#include <bitcoin/short_channel_id.h>
#include <common/node_id.h>
#include <common/bigsize.h>
#include <bitcoin/block.h>
#include <bitcoin/privkey.h>

enum peer_wire {
        WIRE_INIT = 16,
        WIRE_ERROR = 17,
        WIRE_WARNING = 1,
        WIRE_PING = 18,
        WIRE_PONG = 19,
        WIRE_PEER_STORAGE = 7,
        WIRE_PEER_STORAGE_RETRIEVAL = 9,
        WIRE_TX_ADD_INPUT = 66,
        WIRE_TX_ADD_OUTPUT = 67,
        WIRE_TX_REMOVE_INPUT = 68,
        WIRE_TX_REMOVE_OUTPUT = 69,
        WIRE_TX_COMPLETE = 70,
        WIRE_TX_SIGNATURES = 71,
        WIRE_TX_INIT_RBF = 72,
        WIRE_TX_ACK_RBF = 73,
        WIRE_TX_ABORT = 74,
        WIRE_OPEN_CHANNEL = 32,
        WIRE_ACCEPT_CHANNEL = 33,
        WIRE_FUNDING_CREATED = 34,
        WIRE_FUNDING_SIGNED = 35,
        WIRE_CHANNEL_READY = 36,
        WIRE_OPEN_CHANNEL2 = 64,
        WIRE_ACCEPT_CHANNEL2 = 65,
        WIRE_STFU = 2,
        WIRE_SPLICE = 80,
        WIRE_SPLICE_ACK = 81,
        WIRE_SPLICE_LOCKED = 77,
        WIRE_SHUTDOWN = 38,
        WIRE_CLOSING_SIGNED = 39,
        WIRE_CLOSING_COMPLETE = 40,
        WIRE_CLOSING_SIG = 41,
        WIRE_UPDATE_ADD_HTLC = 128,
        WIRE_UPDATE_FULFILL_HTLC = 130,
        WIRE_UPDATE_FAIL_HTLC = 131,
        WIRE_UPDATE_FAIL_MALFORMED_HTLC = 135,
        WIRE_COMMITMENT_SIGNED = 132,
        WIRE_REVOKE_AND_ACK = 133,
        WIRE_UPDATE_FEE = 134,
        WIRE_UPDATE_BLOCKHEIGHT = 137,
        WIRE_CHANNEL_REESTABLISH = 136,
        WIRE_ANNOUNCEMENT_SIGNATURES = 259,
        WIRE_CHANNEL_ANNOUNCEMENT = 256,
        WIRE_NODE_ANNOUNCEMENT = 257,
        WIRE_CHANNEL_UPDATE = 258,
        WIRE_QUERY_SHORT_CHANNEL_IDS = 261,
        WIRE_REPLY_SHORT_CHANNEL_IDS_END = 262,
        WIRE_QUERY_CHANNEL_RANGE = 263,
        WIRE_REPLY_CHANNEL_RANGE = 264,
        WIRE_GOSSIP_TIMESTAMP_FILTER = 265,
        WIRE_ONION_MESSAGE = 513,
};

const char *peer_wire_name(int e);

/**
 * Determine whether a given message type is defined as a message.
 *
 * Returns true if the message type is part of the message definitions we have
 * generated parsers for, false if it is a custom message that cannot be
 * handled internally.
 */
bool peer_wire_is_defined(u16 type);

struct tlv_init_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	struct bitcoin_blkid *networks;
	u8 *remote_addr;
};
struct tlv_n1 {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	u64 *tlv1;
	struct short_channel_id *tlv2;
        struct tlv_n1_tlv3 *tlv3;
	u16 *tlv4;
};
struct tlv_n2 {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	u64 *tlv1;
	u32 *tlv2;
};
struct tlv_tx_add_input_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	struct bitcoin_txid *shared_input_txid;
};
struct tlv_txsigs_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	secp256k1_ecdsa_signature *shared_input_signature;
};
struct tlv_tx_init_rbf_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	s64 *funding_output_contribution;
        struct tlv_tx_init_rbf_tlvs_require_confirmed_inputs *require_confirmed_inputs;
};
struct tlv_tx_ack_rbf_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	s64 *funding_output_contribution;
        struct tlv_tx_ack_rbf_tlvs_require_confirmed_inputs *require_confirmed_inputs;
};
struct tlv_open_channel_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	u8 *upfront_shutdown_script;
	u8 *channel_type;
};
struct tlv_accept_channel_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	u8 *upfront_shutdown_script;
	u8 *channel_type;
};
struct tlv_channel_ready_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	struct short_channel_id *short_channel_id;
};
struct tlv_opening_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	u8 *upfront_shutdown_script;
	u8 *channel_type;
        struct tlv_opening_tlvs_require_confirmed_inputs *require_confirmed_inputs;
        struct tlv_opening_tlvs_request_funds *request_funds;
};
struct tlv_accept_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	u8 *upfront_shutdown_script;
	u8 *channel_type;
        struct tlv_accept_tlvs_require_confirmed_inputs *require_confirmed_inputs;
        struct tlv_accept_tlvs_will_fund *will_fund;
};
struct tlv_shutdown_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
        struct tlv_shutdown_tlvs_wrong_funding *wrong_funding;
};
struct tlv_closing_signed_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
        struct tlv_closing_signed_tlvs_fee_range *fee_range;
};
struct tlv_closing_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	secp256k1_ecdsa_signature *closer_output_only;
	secp256k1_ecdsa_signature *closee_output_only;
	secp256k1_ecdsa_signature *closer_and_closee_outputs;
};
struct tlv_update_add_htlc_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	struct pubkey *blinded_path;
};
struct tlv_commitment_signed_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
        struct tlv_commitment_signed_tlvs_splice_info *splice_info;
};
struct tlv_channel_reestablish_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	struct bitcoin_txid *next_funding;
	u64 *next_to_send;
	u8 *desired_channel_type;
	u8 *current_channel_type;
	u8 *upgradable_channel_type;
};
struct tlv_node_ann_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	struct lease_rates *option_will_fund;
};
struct tlv_query_short_channel_ids_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
        struct tlv_query_short_channel_ids_tlvs_query_flags *query_flags;
};
struct tlv_query_channel_range_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
	bigsize *query_option;
};
struct tlv_reply_channel_range_tlvs {
        /* Raw fields including unknown ones. */
        struct tlv_field *fields;

	/* TODO The following explicit fields could just point into the
	 * tlv_field entries above to save on memory. */
        struct tlv_reply_channel_range_tlvs_timestamps_tlv *timestamps_tlv;
	struct channel_update_checksums *checksums_tlv;
};

struct witness {
        u8 *witness_data;
};
struct lease_rates {
        u16 funding_weight;
        u16 lease_fee_basis;
        u16 channel_fee_max_proportional_thousandths;
        u32 lease_fee_base_sat;
        u32 channel_fee_max_base_msat;
};
struct channel_update_checksums {
        u32 checksum_node_id_1;
        u32 checksum_node_id_2;
};
struct channel_update_timestamps {
        u32 timestamp_node_id_1;
        u32 timestamp_node_id_2;
};
struct tlv_n1_tlv3 {
        struct pubkey node_id;
        struct amount_msat amount_msat_1;
        struct amount_msat amount_msat_2;
};
struct tlv_tx_init_rbf_tlvs_require_confirmed_inputs {
};
struct tlv_tx_ack_rbf_tlvs_require_confirmed_inputs {
};
struct tlv_opening_tlvs_require_confirmed_inputs {
};
struct tlv_opening_tlvs_request_funds {
        u64 requested_sats;
        u32 blockheight;
};
struct tlv_accept_tlvs_require_confirmed_inputs {
};
struct tlv_accept_tlvs_will_fund {
        secp256k1_ecdsa_signature signature;
        struct lease_rates lease_rates;
};
struct tlv_shutdown_tlvs_wrong_funding {
        struct bitcoin_txid txid;
        u32 outnum;
};
struct tlv_closing_signed_tlvs_fee_range {
        struct amount_sat min_fee_satoshis;
        struct amount_sat max_fee_satoshis;
};
struct tlv_commitment_signed_tlvs_splice_info {
        u16 batch_size;
        struct channel_id funding_txid;
};
struct tlv_query_short_channel_ids_tlvs_query_flags {
        u8 encoding_type;
        u8 *encoded_query_flags;
};
struct tlv_reply_channel_range_tlvs_timestamps_tlv {
        u8 encoding_type;
        u8 *encoded_timestamps;
};

struct tlv_init_tlvs *tlv_init_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_init_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_init_tlvs_is_valid.
 */
struct tlv_init_tlvs *fromwire_tlv_init_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_init_tlvs namespace.
 *
 * This function only considers known fields from the tlv_init_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_init_tlvs_is_valid`.
 */
void towire_tlv_init_tlvs(u8 **pptr, const struct tlv_init_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_init_tlvs_is_valid(const struct tlv_init_tlvs *record,
			  size_t *err_index);

struct tlv_n1 *tlv_n1_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_n1 namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_n1_is_valid.
 */
struct tlv_n1 *fromwire_tlv_n1(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_n1 namespace.
 *
 * This function only considers known fields from the tlv_n1 namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_n1_is_valid`.
 */
void towire_tlv_n1(u8 **pptr, const struct tlv_n1 *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_n1_is_valid(const struct tlv_n1 *record,
			  size_t *err_index);

#define TLVS_ARRAY_SIZE_tlv_n1 4
extern const struct tlv_record_type tlvs_tlv_n1[];



/* Define an enum with the constants */
enum tlv_n1_types {
	TLV_N1_TLV1 = 1,
	TLV_N1_TLV2 = 2,
	TLV_N1_TLV3 = 3,
	TLV_N1_TLV4 = 254,
};

struct tlv_n2 *tlv_n2_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_n2 namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_n2_is_valid.
 */
struct tlv_n2 *fromwire_tlv_n2(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_n2 namespace.
 *
 * This function only considers known fields from the tlv_n2 namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_n2_is_valid`.
 */
void towire_tlv_n2(u8 **pptr, const struct tlv_n2 *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_n2_is_valid(const struct tlv_n2 *record,
			  size_t *err_index);

#define TLVS_ARRAY_SIZE_tlv_n2 2
extern const struct tlv_record_type tlvs_tlv_n2[];



/* Define an enum with the constants */
enum tlv_n2_types {
	TLV_N2_TLV1 = 0,
	TLV_N2_TLV2 = 11,
};

struct tlv_tx_add_input_tlvs *tlv_tx_add_input_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_tx_add_input_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_tx_add_input_tlvs_is_valid.
 */
struct tlv_tx_add_input_tlvs *fromwire_tlv_tx_add_input_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_tx_add_input_tlvs namespace.
 *
 * This function only considers known fields from the tlv_tx_add_input_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_tx_add_input_tlvs_is_valid`.
 */
void towire_tlv_tx_add_input_tlvs(u8 **pptr, const struct tlv_tx_add_input_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_tx_add_input_tlvs_is_valid(const struct tlv_tx_add_input_tlvs *record,
			  size_t *err_index);

struct tlv_txsigs_tlvs *tlv_txsigs_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_txsigs_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_txsigs_tlvs_is_valid.
 */
struct tlv_txsigs_tlvs *fromwire_tlv_txsigs_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_txsigs_tlvs namespace.
 *
 * This function only considers known fields from the tlv_txsigs_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_txsigs_tlvs_is_valid`.
 */
void towire_tlv_txsigs_tlvs(u8 **pptr, const struct tlv_txsigs_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_txsigs_tlvs_is_valid(const struct tlv_txsigs_tlvs *record,
			  size_t *err_index);

struct tlv_tx_init_rbf_tlvs *tlv_tx_init_rbf_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_tx_init_rbf_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_tx_init_rbf_tlvs_is_valid.
 */
struct tlv_tx_init_rbf_tlvs *fromwire_tlv_tx_init_rbf_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_tx_init_rbf_tlvs namespace.
 *
 * This function only considers known fields from the tlv_tx_init_rbf_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_tx_init_rbf_tlvs_is_valid`.
 */
void towire_tlv_tx_init_rbf_tlvs(u8 **pptr, const struct tlv_tx_init_rbf_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_tx_init_rbf_tlvs_is_valid(const struct tlv_tx_init_rbf_tlvs *record,
			  size_t *err_index);

struct tlv_tx_ack_rbf_tlvs *tlv_tx_ack_rbf_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_tx_ack_rbf_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_tx_ack_rbf_tlvs_is_valid.
 */
struct tlv_tx_ack_rbf_tlvs *fromwire_tlv_tx_ack_rbf_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_tx_ack_rbf_tlvs namespace.
 *
 * This function only considers known fields from the tlv_tx_ack_rbf_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_tx_ack_rbf_tlvs_is_valid`.
 */
void towire_tlv_tx_ack_rbf_tlvs(u8 **pptr, const struct tlv_tx_ack_rbf_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_tx_ack_rbf_tlvs_is_valid(const struct tlv_tx_ack_rbf_tlvs *record,
			  size_t *err_index);

struct tlv_open_channel_tlvs *tlv_open_channel_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_open_channel_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_open_channel_tlvs_is_valid.
 */
struct tlv_open_channel_tlvs *fromwire_tlv_open_channel_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_open_channel_tlvs namespace.
 *
 * This function only considers known fields from the tlv_open_channel_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_open_channel_tlvs_is_valid`.
 */
void towire_tlv_open_channel_tlvs(u8 **pptr, const struct tlv_open_channel_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_open_channel_tlvs_is_valid(const struct tlv_open_channel_tlvs *record,
			  size_t *err_index);

struct tlv_accept_channel_tlvs *tlv_accept_channel_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_accept_channel_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_accept_channel_tlvs_is_valid.
 */
struct tlv_accept_channel_tlvs *fromwire_tlv_accept_channel_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_accept_channel_tlvs namespace.
 *
 * This function only considers known fields from the tlv_accept_channel_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_accept_channel_tlvs_is_valid`.
 */
void towire_tlv_accept_channel_tlvs(u8 **pptr, const struct tlv_accept_channel_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_accept_channel_tlvs_is_valid(const struct tlv_accept_channel_tlvs *record,
			  size_t *err_index);

struct tlv_channel_ready_tlvs *tlv_channel_ready_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_channel_ready_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_channel_ready_tlvs_is_valid.
 */
struct tlv_channel_ready_tlvs *fromwire_tlv_channel_ready_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_channel_ready_tlvs namespace.
 *
 * This function only considers known fields from the tlv_channel_ready_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_channel_ready_tlvs_is_valid`.
 */
void towire_tlv_channel_ready_tlvs(u8 **pptr, const struct tlv_channel_ready_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_channel_ready_tlvs_is_valid(const struct tlv_channel_ready_tlvs *record,
			  size_t *err_index);

struct tlv_opening_tlvs *tlv_opening_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_opening_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_opening_tlvs_is_valid.
 */
struct tlv_opening_tlvs *fromwire_tlv_opening_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_opening_tlvs namespace.
 *
 * This function only considers known fields from the tlv_opening_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_opening_tlvs_is_valid`.
 */
void towire_tlv_opening_tlvs(u8 **pptr, const struct tlv_opening_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_opening_tlvs_is_valid(const struct tlv_opening_tlvs *record,
			  size_t *err_index);

struct tlv_accept_tlvs *tlv_accept_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_accept_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_accept_tlvs_is_valid.
 */
struct tlv_accept_tlvs *fromwire_tlv_accept_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_accept_tlvs namespace.
 *
 * This function only considers known fields from the tlv_accept_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_accept_tlvs_is_valid`.
 */
void towire_tlv_accept_tlvs(u8 **pptr, const struct tlv_accept_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_accept_tlvs_is_valid(const struct tlv_accept_tlvs *record,
			  size_t *err_index);

struct tlv_shutdown_tlvs *tlv_shutdown_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_shutdown_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_shutdown_tlvs_is_valid.
 */
struct tlv_shutdown_tlvs *fromwire_tlv_shutdown_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_shutdown_tlvs namespace.
 *
 * This function only considers known fields from the tlv_shutdown_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_shutdown_tlvs_is_valid`.
 */
void towire_tlv_shutdown_tlvs(u8 **pptr, const struct tlv_shutdown_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_shutdown_tlvs_is_valid(const struct tlv_shutdown_tlvs *record,
			  size_t *err_index);

struct tlv_closing_signed_tlvs *tlv_closing_signed_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_closing_signed_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_closing_signed_tlvs_is_valid.
 */
struct tlv_closing_signed_tlvs *fromwire_tlv_closing_signed_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_closing_signed_tlvs namespace.
 *
 * This function only considers known fields from the tlv_closing_signed_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_closing_signed_tlvs_is_valid`.
 */
void towire_tlv_closing_signed_tlvs(u8 **pptr, const struct tlv_closing_signed_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_closing_signed_tlvs_is_valid(const struct tlv_closing_signed_tlvs *record,
			  size_t *err_index);

struct tlv_closing_tlvs *tlv_closing_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_closing_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_closing_tlvs_is_valid.
 */
struct tlv_closing_tlvs *fromwire_tlv_closing_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_closing_tlvs namespace.
 *
 * This function only considers known fields from the tlv_closing_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_closing_tlvs_is_valid`.
 */
void towire_tlv_closing_tlvs(u8 **pptr, const struct tlv_closing_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_closing_tlvs_is_valid(const struct tlv_closing_tlvs *record,
			  size_t *err_index);

struct tlv_update_add_htlc_tlvs *tlv_update_add_htlc_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_update_add_htlc_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_update_add_htlc_tlvs_is_valid.
 */
struct tlv_update_add_htlc_tlvs *fromwire_tlv_update_add_htlc_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_update_add_htlc_tlvs namespace.
 *
 * This function only considers known fields from the tlv_update_add_htlc_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_update_add_htlc_tlvs_is_valid`.
 */
void towire_tlv_update_add_htlc_tlvs(u8 **pptr, const struct tlv_update_add_htlc_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_update_add_htlc_tlvs_is_valid(const struct tlv_update_add_htlc_tlvs *record,
			  size_t *err_index);

struct tlv_commitment_signed_tlvs *tlv_commitment_signed_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_commitment_signed_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_commitment_signed_tlvs_is_valid.
 */
struct tlv_commitment_signed_tlvs *fromwire_tlv_commitment_signed_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_commitment_signed_tlvs namespace.
 *
 * This function only considers known fields from the tlv_commitment_signed_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_commitment_signed_tlvs_is_valid`.
 */
void towire_tlv_commitment_signed_tlvs(u8 **pptr, const struct tlv_commitment_signed_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_commitment_signed_tlvs_is_valid(const struct tlv_commitment_signed_tlvs *record,
			  size_t *err_index);

struct tlv_channel_reestablish_tlvs *tlv_channel_reestablish_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_channel_reestablish_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_channel_reestablish_tlvs_is_valid.
 */
struct tlv_channel_reestablish_tlvs *fromwire_tlv_channel_reestablish_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_channel_reestablish_tlvs namespace.
 *
 * This function only considers known fields from the tlv_channel_reestablish_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_channel_reestablish_tlvs_is_valid`.
 */
void towire_tlv_channel_reestablish_tlvs(u8 **pptr, const struct tlv_channel_reestablish_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_channel_reestablish_tlvs_is_valid(const struct tlv_channel_reestablish_tlvs *record,
			  size_t *err_index);

struct tlv_node_ann_tlvs *tlv_node_ann_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_node_ann_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_node_ann_tlvs_is_valid.
 */
struct tlv_node_ann_tlvs *fromwire_tlv_node_ann_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_node_ann_tlvs namespace.
 *
 * This function only considers known fields from the tlv_node_ann_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_node_ann_tlvs_is_valid`.
 */
void towire_tlv_node_ann_tlvs(u8 **pptr, const struct tlv_node_ann_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_node_ann_tlvs_is_valid(const struct tlv_node_ann_tlvs *record,
			  size_t *err_index);

struct tlv_query_short_channel_ids_tlvs *tlv_query_short_channel_ids_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_query_short_channel_ids_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_query_short_channel_ids_tlvs_is_valid.
 */
struct tlv_query_short_channel_ids_tlvs *fromwire_tlv_query_short_channel_ids_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_query_short_channel_ids_tlvs namespace.
 *
 * This function only considers known fields from the tlv_query_short_channel_ids_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_query_short_channel_ids_tlvs_is_valid`.
 */
void towire_tlv_query_short_channel_ids_tlvs(u8 **pptr, const struct tlv_query_short_channel_ids_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_query_short_channel_ids_tlvs_is_valid(const struct tlv_query_short_channel_ids_tlvs *record,
			  size_t *err_index);

struct tlv_query_channel_range_tlvs *tlv_query_channel_range_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_query_channel_range_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_query_channel_range_tlvs_is_valid.
 */
struct tlv_query_channel_range_tlvs *fromwire_tlv_query_channel_range_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_query_channel_range_tlvs namespace.
 *
 * This function only considers known fields from the tlv_query_channel_range_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_query_channel_range_tlvs_is_valid`.
 */
void towire_tlv_query_channel_range_tlvs(u8 **pptr, const struct tlv_query_channel_range_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_query_channel_range_tlvs_is_valid(const struct tlv_query_channel_range_tlvs *record,
			  size_t *err_index);

struct tlv_reply_channel_range_tlvs *tlv_reply_channel_range_tlvs_new(const tal_t *ctx);

/**
 * Deserialize a TLV stream for the tlv_reply_channel_range_tlvs namespace.
 *
 * This function will parse any TLV stream, as long as the type, length and
 * value fields are formatted correctly. Fields that are not known in the
 * current namespace are stored in the `fields` member. Validity can be
 * checked using tlv_reply_channel_range_tlvs_is_valid.
 */
struct tlv_reply_channel_range_tlvs *fromwire_tlv_reply_channel_range_tlvs(const tal_t *ctx,
						  const u8 **cursor, size_t *max);

/**
 * Serialize a TLV stream for the tlv_reply_channel_range_tlvs namespace.
 *
 * This function only considers known fields from the tlv_reply_channel_range_tlvs namespace,
 * and will ignore any fields that may be stored in the `fields` member. This
 * ensures that the resulting stream is valid according to
 * `tlv_reply_channel_range_tlvs_is_valid`.
 */
void towire_tlv_reply_channel_range_tlvs(u8 **pptr, const struct tlv_reply_channel_range_tlvs *record);

/**
 * Check that the TLV stream is valid.
 *
 * Enforces the followin validity rules:
 * - Types must be in monotonic non-repeating order
 * - We must understand all even types
 *
 * Returns false if an error was detected, otherwise returns true. If err_index
 * is non-null and we detect an error it is set to the index of the first error
 * detected.
 */
bool tlv_reply_channel_range_tlvs_is_valid(const struct tlv_reply_channel_range_tlvs *record,
			  size_t *err_index);

/* SUBTYPE: WITNESS */
void towire_witness(u8 **p, const struct witness *witness);
struct witness *fromwire_witness(const tal_t *ctx, const u8 **cursor, size_t *plen);

/* SUBTYPE: LEASE_RATES */
void towire_lease_rates(u8 **p, const struct lease_rates *lease_rates);
bool fromwire_lease_rates(const u8 **cursor, size_t *plen, struct lease_rates *lease_rates);

/* SUBTYPE: CHANNEL_UPDATE_CHECKSUMS */
void towire_channel_update_checksums(u8 **p, const struct channel_update_checksums *channel_update_checksums);
bool fromwire_channel_update_checksums(const u8 **cursor, size_t *plen, struct channel_update_checksums *channel_update_checksums);

/* SUBTYPE: CHANNEL_UPDATE_TIMESTAMPS */
void towire_channel_update_timestamps(u8 **p, const struct channel_update_timestamps *channel_update_timestamps);
bool fromwire_channel_update_timestamps(const u8 **cursor, size_t *plen, struct channel_update_timestamps *channel_update_timestamps);

/* WIRE: INIT */
u8 *towire_init(const tal_t *ctx, const u8 *globalfeatures, const u8 *features, const struct tlv_init_tlvs *tlvs);
bool fromwire_init(const tal_t *ctx, const void *p, u8 **globalfeatures, u8 **features, struct tlv_init_tlvs **tlvs);

/* WIRE: ERROR */
u8 *towire_error(const tal_t *ctx, const struct channel_id *channel_id, const u8 *data);
bool fromwire_error(const tal_t *ctx, const void *p, struct channel_id *channel_id, u8 **data);

/* WIRE: WARNING */
u8 *towire_warning(const tal_t *ctx, const struct channel_id *channel_id, const u8 *data);
bool fromwire_warning(const tal_t *ctx, const void *p, struct channel_id *channel_id, u8 **data);

/* WIRE: PING */
u8 *towire_ping(const tal_t *ctx, u16 num_pong_bytes, const u8 *ignored);
bool fromwire_ping(const tal_t *ctx, const void *p, u16 *num_pong_bytes, u8 **ignored);

/* WIRE: PONG */
u8 *towire_pong(const tal_t *ctx, const u8 *ignored);
bool fromwire_pong(const tal_t *ctx, const void *p, u8 **ignored);

/* WIRE: PEER_STORAGE */
u8 *towire_peer_storage(const tal_t *ctx, const u8 *blob);
bool fromwire_peer_storage(const tal_t *ctx, const void *p, u8 **blob);

/* WIRE: PEER_STORAGE_RETRIEVAL */
u8 *towire_peer_storage_retrieval(const tal_t *ctx, const u8 *blob);
bool fromwire_peer_storage_retrieval(const tal_t *ctx, const void *p, u8 **blob);

/* WIRE: TX_ADD_INPUT */
u8 *towire_tx_add_input(const tal_t *ctx, const struct channel_id *channel_id, u64 serial_id, const u8 *prevtx, u32 prevtx_vout, u32 sequence, const struct tlv_tx_add_input_tlvs *tlvs);
bool fromwire_tx_add_input(const tal_t *ctx, const void *p, struct channel_id *channel_id, u64 *serial_id, u8 **prevtx, u32 *prevtx_vout, u32 *sequence, struct tlv_tx_add_input_tlvs **tlvs);

/* WIRE: TX_ADD_OUTPUT */
u8 *towire_tx_add_output(const tal_t *ctx, const struct channel_id *channel_id, u64 serial_id, u64 sats, const u8 *script);
bool fromwire_tx_add_output(const tal_t *ctx, const void *p, struct channel_id *channel_id, u64 *serial_id, u64 *sats, u8 **script);

/* WIRE: TX_REMOVE_INPUT */
u8 *towire_tx_remove_input(const tal_t *ctx, const struct channel_id *channel_id, u64 serial_id);
bool fromwire_tx_remove_input(const void *p, struct channel_id *channel_id, u64 *serial_id);

/* WIRE: TX_REMOVE_OUTPUT */
u8 *towire_tx_remove_output(const tal_t *ctx, const struct channel_id *channel_id, u64 serial_id);
bool fromwire_tx_remove_output(const void *p, struct channel_id *channel_id, u64 *serial_id);

/* WIRE: TX_COMPLETE */
u8 *towire_tx_complete(const tal_t *ctx, const struct channel_id *channel_id);
bool fromwire_tx_complete(const void *p, struct channel_id *channel_id);

/* WIRE: TX_SIGNATURES */
u8 *towire_tx_signatures(const tal_t *ctx, const struct channel_id *channel_id, const struct bitcoin_txid *txid, const struct witness **witnesses, const struct tlv_txsigs_tlvs *tlvs);
bool fromwire_tx_signatures(const tal_t *ctx, const void *p, struct channel_id *channel_id, struct bitcoin_txid *txid, struct witness ***witnesses, struct tlv_txsigs_tlvs **tlvs);

/* WIRE: TX_INIT_RBF */
u8 *towire_tx_init_rbf(const tal_t *ctx, const struct channel_id *channel_id, u32 locktime, u32 feerate, const struct tlv_tx_init_rbf_tlvs *tlvs);
bool fromwire_tx_init_rbf(const tal_t *ctx, const void *p, struct channel_id *channel_id, u32 *locktime, u32 *feerate, struct tlv_tx_init_rbf_tlvs **tlvs);

/* WIRE: TX_ACK_RBF */
u8 *towire_tx_ack_rbf(const tal_t *ctx, const struct channel_id *channel_id, const struct tlv_tx_ack_rbf_tlvs *tlvs);
bool fromwire_tx_ack_rbf(const tal_t *ctx, const void *p, struct channel_id *channel_id, struct tlv_tx_ack_rbf_tlvs **tlvs);

/* WIRE: TX_ABORT */
u8 *towire_tx_abort(const tal_t *ctx, const struct channel_id *channel_id, const u8 *data);
bool fromwire_tx_abort(const tal_t *ctx, const void *p, struct channel_id *channel_id, u8 **data);

/* WIRE: OPEN_CHANNEL */
u8 *towire_open_channel(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, const struct channel_id *temporary_channel_id, struct amount_sat funding_satoshis, struct amount_msat push_msat, struct amount_sat dust_limit_satoshis, struct amount_msat max_htlc_value_in_flight_msat, struct amount_sat channel_reserve_satoshis, struct amount_msat htlc_minimum_msat, u32 feerate_per_kw, u16 to_self_delay, u16 max_accepted_htlcs, const struct pubkey *funding_pubkey, const struct pubkey *revocation_basepoint, const struct pubkey *payment_basepoint, const struct pubkey *delayed_payment_basepoint, const struct pubkey *htlc_basepoint, const struct pubkey *first_per_commitment_point, u8 channel_flags, const struct tlv_open_channel_tlvs *tlvs);
bool fromwire_open_channel(const tal_t *ctx, const void *p, struct bitcoin_blkid *chain_hash, struct channel_id *temporary_channel_id, struct amount_sat *funding_satoshis, struct amount_msat *push_msat, struct amount_sat *dust_limit_satoshis, struct amount_msat *max_htlc_value_in_flight_msat, struct amount_sat *channel_reserve_satoshis, struct amount_msat *htlc_minimum_msat, u32 *feerate_per_kw, u16 *to_self_delay, u16 *max_accepted_htlcs, struct pubkey *funding_pubkey, struct pubkey *revocation_basepoint, struct pubkey *payment_basepoint, struct pubkey *delayed_payment_basepoint, struct pubkey *htlc_basepoint, struct pubkey *first_per_commitment_point, u8 *channel_flags, struct tlv_open_channel_tlvs **tlvs);

/* WIRE: ACCEPT_CHANNEL */
u8 *towire_accept_channel(const tal_t *ctx, const struct channel_id *temporary_channel_id, struct amount_sat dust_limit_satoshis, struct amount_msat max_htlc_value_in_flight_msat, struct amount_sat channel_reserve_satoshis, struct amount_msat htlc_minimum_msat, u32 minimum_depth, u16 to_self_delay, u16 max_accepted_htlcs, const struct pubkey *funding_pubkey, const struct pubkey *revocation_basepoint, const struct pubkey *payment_basepoint, const struct pubkey *delayed_payment_basepoint, const struct pubkey *htlc_basepoint, const struct pubkey *first_per_commitment_point, const struct tlv_accept_channel_tlvs *tlvs);
bool fromwire_accept_channel(const tal_t *ctx, const void *p, struct channel_id *temporary_channel_id, struct amount_sat *dust_limit_satoshis, struct amount_msat *max_htlc_value_in_flight_msat, struct amount_sat *channel_reserve_satoshis, struct amount_msat *htlc_minimum_msat, u32 *minimum_depth, u16 *to_self_delay, u16 *max_accepted_htlcs, struct pubkey *funding_pubkey, struct pubkey *revocation_basepoint, struct pubkey *payment_basepoint, struct pubkey *delayed_payment_basepoint, struct pubkey *htlc_basepoint, struct pubkey *first_per_commitment_point, struct tlv_accept_channel_tlvs **tlvs);

/* WIRE: FUNDING_CREATED */
u8 *towire_funding_created(const tal_t *ctx, const struct channel_id *temporary_channel_id, const struct bitcoin_txid *funding_txid, u16 funding_output_index, const secp256k1_ecdsa_signature *signature);
bool fromwire_funding_created(const void *p, struct channel_id *temporary_channel_id, struct bitcoin_txid *funding_txid, u16 *funding_output_index, secp256k1_ecdsa_signature *signature);

/* WIRE: FUNDING_SIGNED */
u8 *towire_funding_signed(const tal_t *ctx, const struct channel_id *channel_id, const secp256k1_ecdsa_signature *signature);
bool fromwire_funding_signed(const void *p, struct channel_id *channel_id, secp256k1_ecdsa_signature *signature);

/* WIRE: CHANNEL_READY */
u8 *towire_channel_ready(const tal_t *ctx, const struct channel_id *channel_id, const struct pubkey *second_per_commitment_point, const struct tlv_channel_ready_tlvs *tlvs);
bool fromwire_channel_ready(const tal_t *ctx, const void *p, struct channel_id *channel_id, struct pubkey *second_per_commitment_point, struct tlv_channel_ready_tlvs **tlvs);

/* WIRE: OPEN_CHANNEL2 */
u8 *towire_open_channel2(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, const struct channel_id *temporary_channel_id, u32 funding_feerate_perkw, u32 commitment_feerate_perkw, struct amount_sat funding_satoshis, struct amount_sat dust_limit_satoshis, struct amount_msat max_htlc_value_in_flight_msat, struct amount_msat htlc_minimum_msat, u16 to_self_delay, u16 max_accepted_htlcs, u32 locktime, const struct pubkey *funding_pubkey, const struct pubkey *revocation_basepoint, const struct pubkey *payment_basepoint, const struct pubkey *delayed_payment_basepoint, const struct pubkey *htlc_basepoint, const struct pubkey *first_per_commitment_point, const struct pubkey *second_per_commitment_point, u8 channel_flags, const struct tlv_opening_tlvs *tlvs);
bool fromwire_open_channel2(const tal_t *ctx, const void *p, struct bitcoin_blkid *chain_hash, struct channel_id *temporary_channel_id, u32 *funding_feerate_perkw, u32 *commitment_feerate_perkw, struct amount_sat *funding_satoshis, struct amount_sat *dust_limit_satoshis, struct amount_msat *max_htlc_value_in_flight_msat, struct amount_msat *htlc_minimum_msat, u16 *to_self_delay, u16 *max_accepted_htlcs, u32 *locktime, struct pubkey *funding_pubkey, struct pubkey *revocation_basepoint, struct pubkey *payment_basepoint, struct pubkey *delayed_payment_basepoint, struct pubkey *htlc_basepoint, struct pubkey *first_per_commitment_point, struct pubkey *second_per_commitment_point, u8 *channel_flags, struct tlv_opening_tlvs **tlvs);

/* WIRE: ACCEPT_CHANNEL2 */
u8 *towire_accept_channel2(const tal_t *ctx, const struct channel_id *temporary_channel_id, struct amount_sat funding_satoshis, struct amount_sat dust_limit_satoshis, struct amount_msat max_htlc_value_in_flight_msat, struct amount_msat htlc_minimum_msat, u32 minimum_depth, u16 to_self_delay, u16 max_accepted_htlcs, const struct pubkey *funding_pubkey, const struct pubkey *revocation_basepoint, const struct pubkey *payment_basepoint, const struct pubkey *delayed_payment_basepoint, const struct pubkey *htlc_basepoint, const struct pubkey *first_per_commitment_point, const struct pubkey *second_per_commitment_point, const struct tlv_accept_tlvs *tlvs);
bool fromwire_accept_channel2(const tal_t *ctx, const void *p, struct channel_id *temporary_channel_id, struct amount_sat *funding_satoshis, struct amount_sat *dust_limit_satoshis, struct amount_msat *max_htlc_value_in_flight_msat, struct amount_msat *htlc_minimum_msat, u32 *minimum_depth, u16 *to_self_delay, u16 *max_accepted_htlcs, struct pubkey *funding_pubkey, struct pubkey *revocation_basepoint, struct pubkey *payment_basepoint, struct pubkey *delayed_payment_basepoint, struct pubkey *htlc_basepoint, struct pubkey *first_per_commitment_point, struct pubkey *second_per_commitment_point, struct tlv_accept_tlvs **tlvs);

/* WIRE: STFU */
u8 *towire_stfu(const tal_t *ctx, const struct channel_id *channel_id, u8 initiator);
bool fromwire_stfu(const void *p, struct channel_id *channel_id, u8 *initiator);

/* WIRE: SPLICE */
u8 *towire_splice(const tal_t *ctx, const struct channel_id *channel_id, s64 relative_satoshis, u32 funding_feerate_perkw, u32 locktime, const struct pubkey *funding_pubkey);
bool fromwire_splice(const void *p, struct channel_id *channel_id, s64 *relative_satoshis, u32 *funding_feerate_perkw, u32 *locktime, struct pubkey *funding_pubkey);

/* WIRE: SPLICE_ACK */
u8 *towire_splice_ack(const tal_t *ctx, const struct channel_id *channel_id, s64 relative_satoshis, const struct pubkey *funding_pubkey);
bool fromwire_splice_ack(const void *p, struct channel_id *channel_id, s64 *relative_satoshis, struct pubkey *funding_pubkey);

/* WIRE: SPLICE_LOCKED */
u8 *towire_splice_locked(const tal_t *ctx, const struct channel_id *channel_id);
bool fromwire_splice_locked(const void *p, struct channel_id *channel_id);

/* WIRE: SHUTDOWN */
u8 *towire_shutdown(const tal_t *ctx, const struct channel_id *channel_id, const u8 *scriptpubkey, const struct tlv_shutdown_tlvs *tlvs);
bool fromwire_shutdown(const tal_t *ctx, const void *p, struct channel_id *channel_id, u8 **scriptpubkey, struct tlv_shutdown_tlvs **tlvs);

/* WIRE: CLOSING_SIGNED */
u8 *towire_closing_signed(const tal_t *ctx, const struct channel_id *channel_id, struct amount_sat fee_satoshis, const secp256k1_ecdsa_signature *signature, const struct tlv_closing_signed_tlvs *tlvs);
bool fromwire_closing_signed(const tal_t *ctx, const void *p, struct channel_id *channel_id, struct amount_sat *fee_satoshis, secp256k1_ecdsa_signature *signature, struct tlv_closing_signed_tlvs **tlvs);

/* WIRE: CLOSING_COMPLETE */
u8 *towire_closing_complete(const tal_t *ctx, const struct channel_id *channel_id, const u8 *closer_scriptpubkey, const u8 *closee_scriptpubkey, struct amount_sat fee_satoshis, u32 locktime, const struct tlv_closing_tlvs *tlvs);
bool fromwire_closing_complete(const tal_t *ctx, const void *p, struct channel_id *channel_id, u8 **closer_scriptpubkey, u8 **closee_scriptpubkey, struct amount_sat *fee_satoshis, u32 *locktime, struct tlv_closing_tlvs **tlvs);

/* WIRE: CLOSING_SIG */
u8 *towire_closing_sig(const tal_t *ctx, const struct channel_id *channel_id, const u8 *closer_scriptpubkey, const u8 *closee_scriptpubkey, struct amount_sat fee_satoshis, u32 locktime, const struct tlv_closing_tlvs *tlvs);
bool fromwire_closing_sig(const tal_t *ctx, const void *p, struct channel_id *channel_id, u8 **closer_scriptpubkey, u8 **closee_scriptpubkey, struct amount_sat *fee_satoshis, u32 *locktime, struct tlv_closing_tlvs **tlvs);

/* WIRE: UPDATE_ADD_HTLC */
u8 *towire_update_add_htlc(const tal_t *ctx, const struct channel_id *channel_id, u64 id, struct amount_msat amount_msat, const struct sha256 *payment_hash, u32 cltv_expiry, const u8 onion_routing_packet[1366], const struct tlv_update_add_htlc_tlvs *update_add_htlc);
bool fromwire_update_add_htlc(const tal_t *ctx, const void *p, struct channel_id *channel_id, u64 *id, struct amount_msat *amount_msat, struct sha256 *payment_hash, u32 *cltv_expiry, u8 onion_routing_packet[1366], struct tlv_update_add_htlc_tlvs **update_add_htlc);

/* WIRE: UPDATE_FULFILL_HTLC */
u8 *towire_update_fulfill_htlc(const tal_t *ctx, const struct channel_id *channel_id, u64 id, const struct preimage *payment_preimage);
bool fromwire_update_fulfill_htlc(const void *p, struct channel_id *channel_id, u64 *id, struct preimage *payment_preimage);

/* WIRE: UPDATE_FAIL_HTLC */
u8 *towire_update_fail_htlc(const tal_t *ctx, const struct channel_id *channel_id, u64 id, const u8 *reason);
bool fromwire_update_fail_htlc(const tal_t *ctx, const void *p, struct channel_id *channel_id, u64 *id, u8 **reason);

/* WIRE: UPDATE_FAIL_MALFORMED_HTLC */
u8 *towire_update_fail_malformed_htlc(const tal_t *ctx, const struct channel_id *channel_id, u64 id, const struct sha256 *sha256_of_onion, u16 failure_code);
bool fromwire_update_fail_malformed_htlc(const void *p, struct channel_id *channel_id, u64 *id, struct sha256 *sha256_of_onion, u16 *failure_code);

/* WIRE: COMMITMENT_SIGNED */
u8 *towire_commitment_signed(const tal_t *ctx, const struct channel_id *channel_id, const secp256k1_ecdsa_signature *signature, const secp256k1_ecdsa_signature *htlc_signature, const struct tlv_commitment_signed_tlvs *splice_channel_id);
bool fromwire_commitment_signed(const tal_t *ctx, const void *p, struct channel_id *channel_id, secp256k1_ecdsa_signature *signature, secp256k1_ecdsa_signature **htlc_signature, struct tlv_commitment_signed_tlvs **splice_channel_id);

/* WIRE: REVOKE_AND_ACK */
u8 *towire_revoke_and_ack(const tal_t *ctx, const struct channel_id *channel_id, const struct secret *per_commitment_secret, const struct pubkey *next_per_commitment_point);
bool fromwire_revoke_and_ack(const void *p, struct channel_id *channel_id, struct secret *per_commitment_secret, struct pubkey *next_per_commitment_point);

/* WIRE: UPDATE_FEE */
u8 *towire_update_fee(const tal_t *ctx, const struct channel_id *channel_id, u32 feerate_per_kw);
bool fromwire_update_fee(const void *p, struct channel_id *channel_id, u32 *feerate_per_kw);

/* WIRE: UPDATE_BLOCKHEIGHT */
u8 *towire_update_blockheight(const tal_t *ctx, const struct channel_id *channel_id, u32 blockheight);
bool fromwire_update_blockheight(const void *p, struct channel_id *channel_id, u32 *blockheight);

/* WIRE: CHANNEL_REESTABLISH */
u8 *towire_channel_reestablish(const tal_t *ctx, const struct channel_id *channel_id, u64 next_commitment_number, u64 next_revocation_number, const struct secret *your_last_per_commitment_secret, const struct pubkey *my_current_per_commitment_point, const struct tlv_channel_reestablish_tlvs *channel_reestablish);
bool fromwire_channel_reestablish(const tal_t *ctx, const void *p, struct channel_id *channel_id, u64 *next_commitment_number, u64 *next_revocation_number, struct secret *your_last_per_commitment_secret, struct pubkey *my_current_per_commitment_point, struct tlv_channel_reestablish_tlvs **channel_reestablish);

/* WIRE: ANNOUNCEMENT_SIGNATURES */
u8 *towire_announcement_signatures(const tal_t *ctx, const struct channel_id *channel_id, struct short_channel_id short_channel_id, const secp256k1_ecdsa_signature *node_signature, const secp256k1_ecdsa_signature *bitcoin_signature);
bool fromwire_announcement_signatures(const void *p, struct channel_id *channel_id, struct short_channel_id *short_channel_id, secp256k1_ecdsa_signature *node_signature, secp256k1_ecdsa_signature *bitcoin_signature);

/* WIRE: CHANNEL_ANNOUNCEMENT */
u8 *towire_channel_announcement(const tal_t *ctx, const secp256k1_ecdsa_signature *node_signature_1, const secp256k1_ecdsa_signature *node_signature_2, const secp256k1_ecdsa_signature *bitcoin_signature_1, const secp256k1_ecdsa_signature *bitcoin_signature_2, const u8 *features, const struct bitcoin_blkid *chain_hash, struct short_channel_id short_channel_id, const struct node_id *node_id_1, const struct node_id *node_id_2, const struct pubkey *bitcoin_key_1, const struct pubkey *bitcoin_key_2);
bool fromwire_channel_announcement(const tal_t *ctx, const void *p, secp256k1_ecdsa_signature *node_signature_1, secp256k1_ecdsa_signature *node_signature_2, secp256k1_ecdsa_signature *bitcoin_signature_1, secp256k1_ecdsa_signature *bitcoin_signature_2, u8 **features, struct bitcoin_blkid *chain_hash, struct short_channel_id *short_channel_id, struct node_id *node_id_1, struct node_id *node_id_2, struct pubkey *bitcoin_key_1, struct pubkey *bitcoin_key_2);

/* WIRE: NODE_ANNOUNCEMENT */
u8 *towire_node_announcement(const tal_t *ctx, const secp256k1_ecdsa_signature *signature, const u8 *features, u32 timestamp, const struct node_id *node_id, const u8 rgb_color[3], const u8 alias[32], const u8 *addresses, const struct tlv_node_ann_tlvs *tlvs);
bool fromwire_node_announcement(const tal_t *ctx, const void *p, secp256k1_ecdsa_signature *signature, u8 **features, u32 *timestamp, struct node_id *node_id, u8 rgb_color[3], u8 alias[32], u8 **addresses, struct tlv_node_ann_tlvs **tlvs);

/* WIRE: CHANNEL_UPDATE */
u8 *towire_channel_update(const tal_t *ctx, const secp256k1_ecdsa_signature *signature, const struct bitcoin_blkid *chain_hash, struct short_channel_id short_channel_id, u32 timestamp, u8 message_flags, u8 channel_flags, u16 cltv_expiry_delta, struct amount_msat htlc_minimum_msat, u32 fee_base_msat, u32 fee_proportional_millionths, struct amount_msat htlc_maximum_msat);
bool fromwire_channel_update(const void *p, secp256k1_ecdsa_signature *signature, struct bitcoin_blkid *chain_hash, struct short_channel_id *short_channel_id, u32 *timestamp, u8 *message_flags, u8 *channel_flags, u16 *cltv_expiry_delta, struct amount_msat *htlc_minimum_msat, u32 *fee_base_msat, u32 *fee_proportional_millionths, struct amount_msat *htlc_maximum_msat);

/* WIRE: QUERY_SHORT_CHANNEL_IDS */
u8 *towire_query_short_channel_ids(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, const u8 *encoded_short_ids, const struct tlv_query_short_channel_ids_tlvs *tlvs);
bool fromwire_query_short_channel_ids(const tal_t *ctx, const void *p, struct bitcoin_blkid *chain_hash, u8 **encoded_short_ids, struct tlv_query_short_channel_ids_tlvs **tlvs);

/* WIRE: REPLY_SHORT_CHANNEL_IDS_END */
u8 *towire_reply_short_channel_ids_end(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, u8 full_information);
bool fromwire_reply_short_channel_ids_end(const void *p, struct bitcoin_blkid *chain_hash, u8 *full_information);

/* WIRE: QUERY_CHANNEL_RANGE */
u8 *towire_query_channel_range(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, u32 first_blocknum, u32 number_of_blocks, const struct tlv_query_channel_range_tlvs *tlvs);
bool fromwire_query_channel_range(const tal_t *ctx, const void *p, struct bitcoin_blkid *chain_hash, u32 *first_blocknum, u32 *number_of_blocks, struct tlv_query_channel_range_tlvs **tlvs);

/* WIRE: REPLY_CHANNEL_RANGE */
u8 *towire_reply_channel_range(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, u32 first_blocknum, u32 number_of_blocks, u8 sync_complete, const u8 *encoded_short_ids, const struct tlv_reply_channel_range_tlvs *tlvs);
bool fromwire_reply_channel_range(const tal_t *ctx, const void *p, struct bitcoin_blkid *chain_hash, u32 *first_blocknum, u32 *number_of_blocks, u8 *sync_complete, u8 **encoded_short_ids, struct tlv_reply_channel_range_tlvs **tlvs);

/* WIRE: GOSSIP_TIMESTAMP_FILTER */
u8 *towire_gossip_timestamp_filter(const tal_t *ctx, const struct bitcoin_blkid *chain_hash, u32 first_timestamp, u32 timestamp_range);
bool fromwire_gossip_timestamp_filter(const void *p, struct bitcoin_blkid *chain_hash, u32 *first_timestamp, u32 *timestamp_range);

/* WIRE: ONION_MESSAGE */
u8 *towire_onion_message(const tal_t *ctx, const struct pubkey *path_key, const u8 *onionmsg);
bool fromwire_onion_message(const tal_t *ctx, const void *p, struct pubkey *path_key, u8 **onionmsg);


#endif /* LIGHTNING_WIRE_PEER_WIREGEN_H */
// SHA256STAMP:132292dc8dbd8f307603f60ba5a449e5cf091843acbb3b132a75d4986c59ddf9
