[lib]
name = "rust_bitcoin_lib"
crate-type = ["staticlib"]

[package]
name = "rust_bitcoin_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "a7a8c3b57a906f25234eadcb49230be402a9c75f" }
p2p = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "a7a8c3b57a906f25234eadcb49230be402a9c75f", package = "bitcoin-p2p-messages" }
