all: module.a

CXXFLAGS += -Wall -Wextra -fsanitize=address,fuzzer -std=c++20 -I ../../include

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
  RUST_LIB_EXT := dylib
else
  RUST_LIB_EXT := so
endif

RUST_MINISCRIPT_LIB_PATH := ./rust_miniscript_lib/target/release/librust_miniscript_lib.$(RUST_LIB_EXT)

$(RUST_MINISCRIPT_LIB_PATH):
	cd rust_miniscript_lib && \
	RUSTFLAGS="\
		-Z sanitizer=address \
		-C passes=sancov-module \
		-C llvm-args=-sanitizer-coverage-inline-8bit-counters \
		-C llvm-args=-sanitizer-coverage-trace-compares \
		-C llvm-args=-sanitizer-coverage-pc-table \
		-C llvm-args=-sanitizer-coverage-level=4 \
		-C llvm-args=-simplifycfg-branch-fold-threshold=0" \
	cargo +nightly build --release
	cp $(RUST_MINISCRIPT_LIB_PATH) ../../librust_miniscript_lib.$(RUST_LIB_EXT)

cargo: $(RUST_MINISCRIPT_LIB_PATH)

module.a: module.o $(RUST_MINISCRIPT_LIB_PATH)
	ar rcs module.a module.o

module.o: module.cpp module.h
	$(CXX) $(CXXFLAGS) -I . -fPIC -c module.cpp -o module.o

format:
	clang-format -i ./module.cpp ./module.h ./rust_miniscript_lib/rust_miniscript_lib.h
	cd rust_miniscript_lib && cargo fmt

check-format:
	clang-format -Werror --fail-on-incomplete-format -n ./module.cpp ./module.h ./rust_miniscript_lib/rust_miniscript_lib.h
	cd rust_miniscript_lib && cargo fmt --check

clean:
	rm -rf *.o module.a
	cd rust_miniscript_lib && cargo clean

.PHONY: all cargo clean format check-format $(RUST_MINISCRIPT_LIB_PATH)
