/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the .csv file it was generated from. */
/* Original template can be found at tools/gen/impl_template */

#include <channeld/channeld_wiregen.h>
#include <assert.h>
#include <ccan/array_size/array_size.h>
#include <ccan/mem/mem.h>
#include <ccan/tal/str/str.h>
#include <common/utils.h>
#include <stdio.h>
#include <bitcoin/psbt.h>
#include <bitcoin/tx.h>
#include <channeld/inflight.h>
#include <common/bip32.h>
#include <common/blockheight_states.h>
#include <common/cryptomsg.h>
#include <common/channel_config.h>
#include <common/channel_id.h>
#include <common/channel_type.h>
#include <common/derive_basepoints.h>
#include <common/features.h>
#include <common/fee_states.h>
#include <wire/peer_wire.h>
#include <bitcoin/preimage.h>
#include <common/penalty_base.h>
#include <common/htlc_wire.h>
#include <wally_bip32.h>

#ifndef SUPERVERBOSE
#define SUPERVERBOSE(...)
#endif


const char *channeld_wire_name(int e)
{
	static char invalidbuf[sizeof("UNKNOWN ") + STR_MAX_CHARS(e)];

	switch ((enum channeld_wire)e) {
	case WIRE_CHANNELD_INIT: return "WIRE_CHANNELD_INIT";
	case WIRE_CHANNELD_REESTABLISHED: return "WIRE_CHANNELD_REESTABLISHED";
	case WIRE_CHANNELD_FUNDING_DEPTH: return "WIRE_CHANNELD_FUNDING_DEPTH";
	case WIRE_CHANNELD_OFFER_HTLC: return "WIRE_CHANNELD_OFFER_HTLC";
	case WIRE_CHANNELD_OFFER_HTLC_REPLY: return "WIRE_CHANNELD_OFFER_HTLC_REPLY";
	case WIRE_CHANNELD_FULFILL_HTLC: return "WIRE_CHANNELD_FULFILL_HTLC";
	case WIRE_CHANNELD_FAIL_HTLC: return "WIRE_CHANNELD_FAIL_HTLC";
	case WIRE_CHANNELD_GOT_CHANNEL_READY: return "WIRE_CHANNELD_GOT_CHANNEL_READY";
	case WIRE_CHANNELD_GOT_SPLICE_LOCKED: return "WIRE_CHANNELD_GOT_SPLICE_LOCKED";
	case WIRE_CHANNELD_LOCAL_ANCHOR_INFO: return "WIRE_CHANNELD_LOCAL_ANCHOR_INFO";
	case WIRE_CHANNELD_SENDING_COMMITSIG: return "WIRE_CHANNELD_SENDING_COMMITSIG";
	case WIRE_CHANNELD_SENDING_COMMITSIG_REPLY: return "WIRE_CHANNELD_SENDING_COMMITSIG_REPLY";
	case WIRE_CHANNELD_GOT_COMMITSIG: return "WIRE_CHANNELD_GOT_COMMITSIG";
	case WIRE_CHANNELD_GOT_COMMITSIG_REPLY: return "WIRE_CHANNELD_GOT_COMMITSIG_REPLY";
	case WIRE_CHANNELD_GOT_REVOKE: return "WIRE_CHANNELD_GOT_REVOKE";
	case WIRE_CHANNELD_GOT_REVOKE_REPLY: return "WIRE_CHANNELD_GOT_REVOKE_REPLY";
	case WIRE_CHANNELD_SPLICE_INIT: return "WIRE_CHANNELD_SPLICE_INIT";
	case WIRE_CHANNELD_SPLICE_CONFIRMED_INIT: return "WIRE_CHANNELD_SPLICE_CONFIRMED_INIT";
	case WIRE_CHANNELD_SPLICE_UPDATE: return "WIRE_CHANNELD_SPLICE_UPDATE";
	case WIRE_CHANNELD_SPLICE_CONFIRMED_UPDATE: return "WIRE_CHANNELD_SPLICE_CONFIRMED_UPDATE";
	case WIRE_CHANNELD_SPLICE_LOOKUP_TX: return "WIRE_CHANNELD_SPLICE_LOOKUP_TX";
	case WIRE_CHANNELD_SPLICE_LOOKUP_TX_RESULT: return "WIRE_CHANNELD_SPLICE_LOOKUP_TX_RESULT";
	case WIRE_CHANNELD_SPLICE_SIGNED: return "WIRE_CHANNELD_SPLICE_SIGNED";
	case WIRE_CHANNELD_SPLICE_CONFIRMED_SIGNED: return "WIRE_CHANNELD_SPLICE_CONFIRMED_SIGNED";
	case WIRE_CHANNELD_SPLICE_SENDING_SIGS: return "WIRE_CHANNELD_SPLICE_SENDING_SIGS";
	case WIRE_CHANNELD_SPLICE_FEERATE_ERROR: return "WIRE_CHANNELD_SPLICE_FEERATE_ERROR";
	case WIRE_CHANNELD_ADD_INFLIGHT: return "WIRE_CHANNELD_ADD_INFLIGHT";
	case WIRE_CHANNELD_GOT_INFLIGHT: return "WIRE_CHANNELD_GOT_INFLIGHT";
	case WIRE_CHANNELD_UPDATE_INFLIGHT: return "WIRE_CHANNELD_UPDATE_INFLIGHT";
	case WIRE_CHANNELD_SPLICE_FUNDING_ERROR: return "WIRE_CHANNELD_SPLICE_FUNDING_ERROR";
	case WIRE_CHANNELD_SPLICE_STATE_ERROR: return "WIRE_CHANNELD_SPLICE_STATE_ERROR";
	case WIRE_CHANNELD_SPLICE_ABORT: return "WIRE_CHANNELD_SPLICE_ABORT";
	case WIRE_CHANNELD_STFU: return "WIRE_CHANNELD_STFU";
	case WIRE_CHANNELD_CONFIRMED_STFU: return "WIRE_CHANNELD_CONFIRMED_STFU";
	case WIRE_CHANNELD_ABORT: return "WIRE_CHANNELD_ABORT";
	case WIRE_CHANNELD_SEND_SHUTDOWN: return "WIRE_CHANNELD_SEND_SHUTDOWN";
	case WIRE_CHANNELD_GOT_SHUTDOWN: return "WIRE_CHANNELD_GOT_SHUTDOWN";
	case WIRE_CHANNELD_SHUTDOWN_COMPLETE: return "WIRE_CHANNELD_SHUTDOWN_COMPLETE";
	case WIRE_CHANNELD_DEV_REENABLE_COMMIT: return "WIRE_CHANNELD_DEV_REENABLE_COMMIT";
	case WIRE_CHANNELD_DEV_REENABLE_COMMIT_REPLY: return "WIRE_CHANNELD_DEV_REENABLE_COMMIT_REPLY";
	case WIRE_CHANNELD_FEERATES: return "WIRE_CHANNELD_FEERATES";
	case WIRE_CHANNELD_DEV_MEMLEAK: return "WIRE_CHANNELD_DEV_MEMLEAK";
	case WIRE_CHANNELD_DEV_MEMLEAK_REPLY: return "WIRE_CHANNELD_DEV_MEMLEAK_REPLY";
	case WIRE_CHANNELD_FAIL_FALLEN_BEHIND: return "WIRE_CHANNELD_FAIL_FALLEN_BEHIND";
	case WIRE_CHANNELD_GOT_ANNOUNCEMENT: return "WIRE_CHANNELD_GOT_ANNOUNCEMENT";
	case WIRE_CHANNELD_SEND_ERROR: return "WIRE_CHANNELD_SEND_ERROR";
	case WIRE_CHANNELD_SEND_ERROR_REPLY: return "WIRE_CHANNELD_SEND_ERROR_REPLY";
	case WIRE_CHANNELD_DEV_QUIESCE: return "WIRE_CHANNELD_DEV_QUIESCE";
	case WIRE_CHANNELD_DEV_QUIESCE_REPLY: return "WIRE_CHANNELD_DEV_QUIESCE_REPLY";
	case WIRE_CHANNELD_UPGRADED: return "WIRE_CHANNELD_UPGRADED";
	case WIRE_CHANNELD_BLOCKHEIGHT: return "WIRE_CHANNELD_BLOCKHEIGHT";
	case WIRE_CHANNELD_DEV_PEER_SHACHAIN: return "WIRE_CHANNELD_DEV_PEER_SHACHAIN";
	}

	snprintf(invalidbuf, sizeof(invalidbuf), "UNKNOWN %i", e);
	return invalidbuf;
}

bool channeld_wire_is_defined(u16 type)
{
	switch ((enum channeld_wire)type) {
	case WIRE_CHANNELD_INIT:;
	case WIRE_CHANNELD_REESTABLISHED:;
	case WIRE_CHANNELD_FUNDING_DEPTH:;
	case WIRE_CHANNELD_OFFER_HTLC:;
	case WIRE_CHANNELD_OFFER_HTLC_REPLY:;
	case WIRE_CHANNELD_FULFILL_HTLC:;
	case WIRE_CHANNELD_FAIL_HTLC:;
	case WIRE_CHANNELD_GOT_CHANNEL_READY:;
	case WIRE_CHANNELD_GOT_SPLICE_LOCKED:;
	case WIRE_CHANNELD_LOCAL_ANCHOR_INFO:;
	case WIRE_CHANNELD_SENDING_COMMITSIG:;
	case WIRE_CHANNELD_SENDING_COMMITSIG_REPLY:;
	case WIRE_CHANNELD_GOT_COMMITSIG:;
	case WIRE_CHANNELD_GOT_COMMITSIG_REPLY:;
	case WIRE_CHANNELD_GOT_REVOKE:;
	case WIRE_CHANNELD_GOT_REVOKE_REPLY:;
	case WIRE_CHANNELD_SPLICE_INIT:;
	case WIRE_CHANNELD_SPLICE_CONFIRMED_INIT:;
	case WIRE_CHANNELD_SPLICE_UPDATE:;
	case WIRE_CHANNELD_SPLICE_CONFIRMED_UPDATE:;
	case WIRE_CHANNELD_SPLICE_LOOKUP_TX:;
	case WIRE_CHANNELD_SPLICE_LOOKUP_TX_RESULT:;
	case WIRE_CHANNELD_SPLICE_SIGNED:;
	case WIRE_CHANNELD_SPLICE_CONFIRMED_SIGNED:;
	case WIRE_CHANNELD_SPLICE_SENDING_SIGS:;
	case WIRE_CHANNELD_SPLICE_FEERATE_ERROR:;
	case WIRE_CHANNELD_ADD_INFLIGHT:;
	case WIRE_CHANNELD_GOT_INFLIGHT:;
	case WIRE_CHANNELD_UPDATE_INFLIGHT:;
	case WIRE_CHANNELD_SPLICE_FUNDING_ERROR:;
	case WIRE_CHANNELD_SPLICE_STATE_ERROR:;
	case WIRE_CHANNELD_SPLICE_ABORT:;
	case WIRE_CHANNELD_STFU:;
	case WIRE_CHANNELD_CONFIRMED_STFU:;
	case WIRE_CHANNELD_ABORT:;
	case WIRE_CHANNELD_SEND_SHUTDOWN:;
	case WIRE_CHANNELD_GOT_SHUTDOWN:;
	case WIRE_CHANNELD_SHUTDOWN_COMPLETE:;
	case WIRE_CHANNELD_DEV_REENABLE_COMMIT:;
	case WIRE_CHANNELD_DEV_REENABLE_COMMIT_REPLY:;
	case WIRE_CHANNELD_FEERATES:;
	case WIRE_CHANNELD_DEV_MEMLEAK:;
	case WIRE_CHANNELD_DEV_MEMLEAK_REPLY:;
	case WIRE_CHANNELD_FAIL_FALLEN_BEHIND:;
	case WIRE_CHANNELD_GOT_ANNOUNCEMENT:;
	case WIRE_CHANNELD_SEND_ERROR:;
	case WIRE_CHANNELD_SEND_ERROR_REPLY:;
	case WIRE_CHANNELD_DEV_QUIESCE:;
	case WIRE_CHANNELD_DEV_QUIESCE_REPLY:;
	case WIRE_CHANNELD_UPGRADED:;
	case WIRE_CHANNELD_BLOCKHEIGHT:;
	case WIRE_CHANNELD_DEV_PEER_SHACHAIN:;
	      return true;
	}
	return false;
}




/* SUBTYPE: LOCAL_ANCHOR_INFO */
static void towire_local_anchor_info(u8 **p, const struct local_anchor_info *local_anchor_info)
{

	towire_u32(p, local_anchor_info->commitment_weight);
	towire_amount_sat(p, local_anchor_info->commitment_fee);
	towire_bitcoin_outpoint(p, &local_anchor_info->anchor_point);
}
static bool fromwire_local_anchor_info(const u8 **cursor, size_t *plen, struct local_anchor_info *local_anchor_info)
{

 	local_anchor_info->commitment_weight = fromwire_u32(cursor, plen);
 	local_anchor_info->commitment_fee = fromwire_amount_sat(cursor, plen);
 	fromwire_bitcoin_outpoint(cursor, plen, &local_anchor_info->anchor_point);

	return *cursor != NULL;
}

/* SUBTYPE: COMMITSIG */
static void towire_commitsig(u8 **p, const struct commitsig *commitsig)
{
	u16 num_htlcs = tal_count(commitsig->htlc_signatures);

	towire_bitcoin_tx(p, commitsig->tx);
	towire_bitcoin_signature(p, &commitsig->commit_signature);
	towire_u16(p, num_htlcs);
		for (size_t i = 0; i < num_htlcs; i++)
		towire_bitcoin_signature(p, commitsig->htlc_signatures + i);
}
static struct commitsig *
fromwire_commitsig(const tal_t *ctx, const u8 **cursor, size_t *plen)
{
	struct commitsig *commitsig = tal(ctx, struct commitsig);
	u16 num_htlcs;

 	commitsig->tx = fromwire_bitcoin_tx(commitsig, cursor, plen);
 	fromwire_bitcoin_signature(cursor, plen, &commitsig->commit_signature);
 	num_htlcs = fromwire_u16(cursor, plen);
 	commitsig->htlc_signatures = num_htlcs ? tal_arr(commitsig, struct bitcoin_signature, 0) : NULL;
	for (size_t i = 0; i < num_htlcs; i++) {
		struct bitcoin_signature tmp;
		fromwire_bitcoin_signature(cursor, plen, &tmp);
		tal_arr_expand(&commitsig->htlc_signatures, tmp);
	}

	return commitsig;
}


/* WIRE: CHANNELD_INIT */
/* Begin!  (passes gossipd-client fd) */
u8 *towire_channeld_init(const tal_t *ctx, const struct chainparams *chainparams, const struct feature_set *our_features, const u32 *hsm_capabilities, const struct channel_id *channel_id, const struct bitcoin_outpoint *funding, struct amount_sat funding_satoshi, u32 minimum_depth, u32 our_blockheight, const struct height_states *blockheight_states, u32 lease_expiry, const struct channel_config *our_config, const struct channel_config *their_config, const struct fee_states *fee_states, u32 feerate_min, u32 feerate_max, u32 feerate_penalty, const struct bitcoin_signature *first_commit_sig, const struct pubkey *remote_fundingkey, const struct basepoints *remote_basepoints, const struct pubkey *remote_per_commit, const struct pubkey *old_remote_per_commit, enum side opener, struct amount_msat local_msatoshi, const struct basepoints *our_basepoints, const struct pubkey *our_funding_pubkey, u32 commit_msec, bool last_was_revoke, const struct changed_htlc *last_sent_commit, u64 next_index_local, u64 next_index_remote, u64 revocations_received, u64 next_htlc_id, const struct existing_htlc **htlcs, bool local_channel_ready, bool remote_channel_ready, struct short_channel_id funding_short_id, bool reestablish, bool send_shutdown, bool remote_shutdown_received, u32 final_index, const struct ext_key *final_ext_key, const u8 *final_scriptpubkey, u8 flags, const u8 *init_peer_pkt, const struct secret *last_remote_secret, const u8 *their_features, const u8 *upfront_shutdown_script, const struct channel_type *desired_type, u32 *dev_disable_commit, const struct penalty_base *pbases, bool reestablish_only, bool experimental_upgrade, const struct inflight **inflights, struct short_channel_id scid_alias)
{
	u16 num_hsm_capabilities = tal_count(hsm_capabilities);
	u16 num_last_sent_commit = tal_count(last_sent_commit);
	u16 num_existing_htlcs = tal_count(htlcs);
	u16 final_scriptpubkey_len = tal_count(final_scriptpubkey);
	u16 init_peer_pkt_len = tal_count(init_peer_pkt);
	u16 flen = tal_count(their_features);
	u16 upfront_shutdown_script_len = tal_count(upfront_shutdown_script);
	u32 num_penalty_bases = tal_count(pbases);
	u16 num_inflights = tal_count(inflights);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_INIT);
	towire_chainparams(&p, chainparams);
	towire_feature_set(&p, our_features);
	towire_u16(&p, num_hsm_capabilities);
	for (size_t i = 0; i < num_hsm_capabilities; i++)
		towire_u32(&p, hsm_capabilities[i]);
	towire_channel_id(&p, channel_id);
	towire_bitcoin_outpoint(&p, funding);
	towire_amount_sat(&p, funding_satoshi);
	towire_u32(&p, minimum_depth);
	towire_u32(&p, our_blockheight);
	towire_height_states(&p, blockheight_states);
	towire_u32(&p, lease_expiry);
	towire_channel_config(&p, our_config);
	towire_channel_config(&p, their_config);
	towire_fee_states(&p, fee_states);
	towire_u32(&p, feerate_min);
	towire_u32(&p, feerate_max);
	towire_u32(&p, feerate_penalty);
	towire_bitcoin_signature(&p, first_commit_sig);
	towire_pubkey(&p, remote_fundingkey);
	towire_basepoints(&p, remote_basepoints);
	towire_pubkey(&p, remote_per_commit);
	towire_pubkey(&p, old_remote_per_commit);
	towire_side(&p, opener);
	towire_amount_msat(&p, local_msatoshi);
	towire_basepoints(&p, our_basepoints);
	towire_pubkey(&p, our_funding_pubkey);
	towire_u32(&p, commit_msec);
	towire_bool(&p, last_was_revoke);
	towire_u16(&p, num_last_sent_commit);
	for (size_t i = 0; i < num_last_sent_commit; i++)
		towire_changed_htlc(&p, last_sent_commit + i);
	towire_u64(&p, next_index_local);
	towire_u64(&p, next_index_remote);
	towire_u64(&p, revocations_received);
	towire_u64(&p, next_htlc_id);
	towire_u16(&p, num_existing_htlcs);
	for (size_t i = 0; i < num_existing_htlcs; i++)
		towire_existing_htlc(&p, htlcs[i]);
	towire_bool(&p, local_channel_ready);
	towire_bool(&p, remote_channel_ready);
	towire_short_channel_id(&p, funding_short_id);
	towire_bool(&p, reestablish);
	towire_bool(&p, send_shutdown);
	towire_bool(&p, remote_shutdown_received);
	towire_u32(&p, final_index);
	towire_ext_key(&p, final_ext_key);
	towire_u16(&p, final_scriptpubkey_len);
	towire_u8_array(&p, final_scriptpubkey, final_scriptpubkey_len);
	towire_u8(&p, flags);
	towire_u16(&p, init_peer_pkt_len);
	towire_u8_array(&p, init_peer_pkt, init_peer_pkt_len);
	towire_secret(&p, last_remote_secret);
	towire_u16(&p, flen);
	towire_u8_array(&p, their_features, flen);
	towire_u16(&p, upfront_shutdown_script_len);
	towire_u8_array(&p, upfront_shutdown_script, upfront_shutdown_script_len);
	towire_channel_type(&p, desired_type);
	if (!dev_disable_commit)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_u32(&p, *dev_disable_commit);
	}
	towire_u32(&p, num_penalty_bases);
	for (size_t i = 0; i < num_penalty_bases; i++)
		towire_penalty_base(&p, pbases + i);
	towire_bool(&p, reestablish_only);
	towire_bool(&p, experimental_upgrade);
	towire_u16(&p, num_inflights);
	for (size_t i = 0; i < num_inflights; i++)
		towire_inflight(&p, inflights[i]);
	towire_short_channel_id(&p, scid_alias);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_init(const tal_t *ctx, const void *p, const struct chainparams **chainparams, struct feature_set **our_features, u32 **hsm_capabilities, struct channel_id *channel_id, struct bitcoin_outpoint *funding, struct amount_sat *funding_satoshi, u32 *minimum_depth, u32 *our_blockheight, struct height_states **blockheight_states, u32 *lease_expiry, struct channel_config *our_config, struct channel_config *their_config, struct fee_states **fee_states, u32 *feerate_min, u32 *feerate_max, u32 *feerate_penalty, struct bitcoin_signature *first_commit_sig, struct pubkey *remote_fundingkey, struct basepoints *remote_basepoints, struct pubkey *remote_per_commit, struct pubkey *old_remote_per_commit, enum side *opener, struct amount_msat *local_msatoshi, struct basepoints *our_basepoints, struct pubkey *our_funding_pubkey, u32 *commit_msec, bool *last_was_revoke, struct changed_htlc **last_sent_commit, u64 *next_index_local, u64 *next_index_remote, u64 *revocations_received, u64 *next_htlc_id, struct existing_htlc ***htlcs, bool *local_channel_ready, bool *remote_channel_ready, struct short_channel_id *funding_short_id, bool *reestablish, bool *send_shutdown, bool *remote_shutdown_received, u32 *final_index, struct ext_key *final_ext_key, u8 **final_scriptpubkey, u8 *flags, u8 **init_peer_pkt, struct secret *last_remote_secret, u8 **their_features, u8 **upfront_shutdown_script, struct channel_type **desired_type, u32 **dev_disable_commit, struct penalty_base **pbases, bool *reestablish_only, bool *experimental_upgrade, struct inflight ***inflights, struct short_channel_id *scid_alias)
{
	u16 num_hsm_capabilities;
	u16 num_last_sent_commit;
	u16 num_existing_htlcs;
	u16 final_scriptpubkey_len;
	u16 init_peer_pkt_len;
	u16 flen;
	u16 upfront_shutdown_script_len;
	u32 num_penalty_bases;
	u16 num_inflights;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_INIT)
		return false;
 	fromwire_chainparams(&cursor, &plen, chainparams);
 	*our_features = fromwire_feature_set(ctx, &cursor, &plen);
 	num_hsm_capabilities = fromwire_u16(&cursor, &plen);
 	// 2nd case hsm_capabilities
	*hsm_capabilities = num_hsm_capabilities ? tal_arr(ctx, u32, num_hsm_capabilities) : NULL;
	for (size_t i = 0; i < num_hsm_capabilities; i++)
		(*hsm_capabilities)[i] = fromwire_u32(&cursor, &plen);
 	fromwire_channel_id(&cursor, &plen, channel_id);
 	fromwire_bitcoin_outpoint(&cursor, &plen, funding);
 	*funding_satoshi = fromwire_amount_sat(&cursor, &plen);
 	*minimum_depth = fromwire_u32(&cursor, &plen);
 	*our_blockheight = fromwire_u32(&cursor, &plen);
 	*blockheight_states = fromwire_height_states(ctx, &cursor, &plen);
 	*lease_expiry = fromwire_u32(&cursor, &plen);
 	fromwire_channel_config(&cursor, &plen, our_config);
 	fromwire_channel_config(&cursor, &plen, their_config);
 	*fee_states = fromwire_fee_states(ctx, &cursor, &plen);
 	*feerate_min = fromwire_u32(&cursor, &plen);
 	*feerate_max = fromwire_u32(&cursor, &plen);
 	*feerate_penalty = fromwire_u32(&cursor, &plen);
 	fromwire_bitcoin_signature(&cursor, &plen, first_commit_sig);
 	fromwire_pubkey(&cursor, &plen, remote_fundingkey);
 	fromwire_basepoints(&cursor, &plen, remote_basepoints);
 	fromwire_pubkey(&cursor, &plen, remote_per_commit);
 	fromwire_pubkey(&cursor, &plen, old_remote_per_commit);
 	*opener = fromwire_side(&cursor, &plen);
 	*local_msatoshi = fromwire_amount_msat(&cursor, &plen);
 	fromwire_basepoints(&cursor, &plen, our_basepoints);
 	fromwire_pubkey(&cursor, &plen, our_funding_pubkey);
 	*commit_msec = fromwire_u32(&cursor, &plen);
 	*last_was_revoke = fromwire_bool(&cursor, &plen);
 	num_last_sent_commit = fromwire_u16(&cursor, &plen);
 	// 2nd case last_sent_commit
	*last_sent_commit = num_last_sent_commit ? tal_arr(ctx, struct changed_htlc, num_last_sent_commit) : NULL;
	for (size_t i = 0; i < num_last_sent_commit; i++)
		fromwire_changed_htlc(&cursor, &plen, *last_sent_commit + i);
 	*next_index_local = fromwire_u64(&cursor, &plen);
 	*next_index_remote = fromwire_u64(&cursor, &plen);
 	*revocations_received = fromwire_u64(&cursor, &plen);
 	*next_htlc_id = fromwire_u64(&cursor, &plen);
 	num_existing_htlcs = fromwire_u16(&cursor, &plen);
 	// 2nd case htlcs
	*htlcs = num_existing_htlcs ? tal_arr(ctx, struct existing_htlc *, num_existing_htlcs) : NULL;
	for (size_t i = 0; i < num_existing_htlcs; i++)
		(*htlcs)[i] = fromwire_existing_htlc(*htlcs, &cursor, &plen);
 	*local_channel_ready = fromwire_bool(&cursor, &plen);
 	*remote_channel_ready = fromwire_bool(&cursor, &plen);
 	*funding_short_id = fromwire_short_channel_id(&cursor, &plen);
 	*reestablish = fromwire_bool(&cursor, &plen);
 	*send_shutdown = fromwire_bool(&cursor, &plen);
 	*remote_shutdown_received = fromwire_bool(&cursor, &plen);
 	*final_index = fromwire_u32(&cursor, &plen);
 	fromwire_ext_key(&cursor, &plen, final_ext_key);
 	final_scriptpubkey_len = fromwire_u16(&cursor, &plen);
 	// 2nd case final_scriptpubkey
	*final_scriptpubkey = final_scriptpubkey_len ? tal_arr(ctx, u8, final_scriptpubkey_len) : NULL;
	fromwire_u8_array(&cursor, &plen, *final_scriptpubkey, final_scriptpubkey_len);
 	*flags = fromwire_u8(&cursor, &plen);
 	init_peer_pkt_len = fromwire_u16(&cursor, &plen);
 	// 2nd case init_peer_pkt
	*init_peer_pkt = init_peer_pkt_len ? tal_arr(ctx, u8, init_peer_pkt_len) : NULL;
	fromwire_u8_array(&cursor, &plen, *init_peer_pkt, init_peer_pkt_len);
 	fromwire_secret(&cursor, &plen, last_remote_secret);
 	flen = fromwire_u16(&cursor, &plen);
 	// 2nd case their_features
	*their_features = flen ? tal_arr(ctx, u8, flen) : NULL;
	fromwire_u8_array(&cursor, &plen, *their_features, flen);
 	upfront_shutdown_script_len = fromwire_u16(&cursor, &plen);
 	// 2nd case upfront_shutdown_script
	*upfront_shutdown_script = upfront_shutdown_script_len ? tal_arr(ctx, u8, upfront_shutdown_script_len) : NULL;
	fromwire_u8_array(&cursor, &plen, *upfront_shutdown_script, upfront_shutdown_script_len);
 	*desired_type = fromwire_channel_type(ctx, &cursor, &plen);
 	if (!fromwire_bool(&cursor, &plen))
		*dev_disable_commit = NULL;
	else {
		*dev_disable_commit = tal(ctx, u32);
		**dev_disable_commit = fromwire_u32(&cursor, &plen);
	}
 	num_penalty_bases = fromwire_u32(&cursor, &plen);
 	// 2nd case pbases
	*pbases = num_penalty_bases ? tal_arr(ctx, struct penalty_base, num_penalty_bases) : NULL;
	for (size_t i = 0; i < num_penalty_bases; i++)
		fromwire_penalty_base(&cursor, &plen, *pbases + i);
 	*reestablish_only = fromwire_bool(&cursor, &plen);
 	*experimental_upgrade = fromwire_bool(&cursor, &plen);
 	num_inflights = fromwire_u16(&cursor, &plen);
 	// 2nd case inflights
	*inflights = num_inflights ? tal_arr(ctx, struct inflight *, num_inflights) : NULL;
	for (size_t i = 0; i < num_inflights; i++)
		(*inflights)[i] = fromwire_inflight(*inflights, &cursor, &plen);
 	*scid_alias = fromwire_short_channel_id(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_REESTABLISHED */
/* channeld->lightningd: successfully negotated reestablishment. */
u8 *towire_channeld_reestablished(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_REESTABLISHED);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_reestablished(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_REESTABLISHED)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_FUNDING_DEPTH */
/* master->channeld funding hit new depth(funding locked if >= lock depth) */
/* short_channel_id != NULL once we have 3+ confirmations */
u8 *towire_channeld_funding_depth(const tal_t *ctx, struct short_channel_id *short_channel_id, u32 depth, bool splicing, const struct bitcoin_txid *txid)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_FUNDING_DEPTH);
	if (!short_channel_id)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_short_channel_id(&p, *short_channel_id);
	}
	towire_u32(&p, depth);
	towire_bool(&p, splicing);
	towire_bitcoin_txid(&p, txid);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_funding_depth(const tal_t *ctx, const void *p, struct short_channel_id **short_channel_id, u32 *depth, bool *splicing, struct bitcoin_txid *txid)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_FUNDING_DEPTH)
		return false;
 	if (!fromwire_bool(&cursor, &plen))
		*short_channel_id = NULL;
	else {
		*short_channel_id = tal(ctx, struct short_channel_id);
		**short_channel_id = fromwire_short_channel_id(&cursor, &plen);
	}
 	*depth = fromwire_u32(&cursor, &plen);
 	*splicing = fromwire_bool(&cursor, &plen);
 	fromwire_bitcoin_txid(&cursor, &plen, txid);
	return cursor != NULL;
}

/* WIRE: CHANNELD_OFFER_HTLC */
/* Tell channel to offer this htlc */
u8 *towire_channeld_offer_htlc(const tal_t *ctx, struct amount_msat amount_msat, u32 cltv_expiry, const struct sha256 *payment_hash, const u8 onion_routing_packet[1366], const struct pubkey *path_key)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_OFFER_HTLC);
	towire_amount_msat(&p, amount_msat);
	towire_u32(&p, cltv_expiry);
	towire_sha256(&p, payment_hash);
	towire_u8_array(&p, onion_routing_packet, 1366);
	if (!path_key)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_pubkey(&p, path_key);
	}

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_offer_htlc(const tal_t *ctx, const void *p, struct amount_msat *amount_msat, u32 *cltv_expiry, struct sha256 *payment_hash, u8 onion_routing_packet[1366], struct pubkey **path_key)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_OFFER_HTLC)
		return false;
 	*amount_msat = fromwire_amount_msat(&cursor, &plen);
 	*cltv_expiry = fromwire_u32(&cursor, &plen);
 	fromwire_sha256(&cursor, &plen, payment_hash);
 	fromwire_u8_array(&cursor, &plen, onion_routing_packet, 1366);
 	if (!fromwire_bool(&cursor, &plen))
		*path_key = NULL;
	else {
		*path_key = tal(ctx, struct pubkey);
		fromwire_pubkey(&cursor, &plen, *path_key);
	}
	return cursor != NULL;
}

/* WIRE: CHANNELD_OFFER_HTLC_REPLY */
/* Reply; synchronous since IDs have to increment. */
u8 *towire_channeld_offer_htlc_reply(const tal_t *ctx, u64 id, const u8 *failuremsg, const wirestring *failurestr)
{
	u16 len = tal_count(failuremsg);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_OFFER_HTLC_REPLY);
	towire_u64(&p, id);
	/* Empty failure message means success. */
	towire_u16(&p, len);
	towire_u8_array(&p, failuremsg, len);
	towire_wirestring(&p, failurestr);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_offer_htlc_reply(const tal_t *ctx, const void *p, u64 *id, u8 **failuremsg, wirestring **failurestr)
{
	u16 len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_OFFER_HTLC_REPLY)
		return false;
 	*id = fromwire_u64(&cursor, &plen);
 	/* Empty failure message means success. */
	len = fromwire_u16(&cursor, &plen);
 	// 2nd case failuremsg
	*failuremsg = len ? tal_arr(ctx, u8, len) : NULL;
	fromwire_u8_array(&cursor, &plen, *failuremsg, len);
 	*failurestr = fromwire_wirestring(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_FULFILL_HTLC */
/* Main daemon found out the preimage for an HTLC */
u8 *towire_channeld_fulfill_htlc(const tal_t *ctx, const struct fulfilled_htlc *fulfilled_htlc)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_FULFILL_HTLC);
	towire_fulfilled_htlc(&p, fulfilled_htlc);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_fulfill_htlc(const void *p, struct fulfilled_htlc *fulfilled_htlc)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_FULFILL_HTLC)
		return false;
 	fromwire_fulfilled_htlc(&cursor, &plen, fulfilled_htlc);
	return cursor != NULL;
}

/* WIRE: CHANNELD_FAIL_HTLC */
/* Main daemon says HTLC failed */
u8 *towire_channeld_fail_htlc(const tal_t *ctx, const struct failed_htlc *failed_htlc)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_FAIL_HTLC);
	towire_failed_htlc(&p, failed_htlc);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_fail_htlc(const tal_t *ctx, const void *p, struct failed_htlc **failed_htlc)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_FAIL_HTLC)
		return false;
 	*failed_htlc = fromwire_failed_htlc(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_CHANNEL_READY */
/* When we receive channel_ready. */
u8 *towire_channeld_got_channel_ready(const tal_t *ctx, const struct pubkey *next_per_commit_point, struct short_channel_id *alias)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_CHANNEL_READY);
	towire_pubkey(&p, next_per_commit_point);
	if (!alias)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_short_channel_id(&p, *alias);
	}

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_channel_ready(const tal_t *ctx, const void *p, struct pubkey *next_per_commit_point, struct short_channel_id **alias)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_CHANNEL_READY)
		return false;
 	fromwire_pubkey(&cursor, &plen, next_per_commit_point);
 	if (!fromwire_bool(&cursor, &plen))
		*alias = NULL;
	else {
		*alias = tal(ctx, struct short_channel_id);
		**alias = fromwire_short_channel_id(&cursor, &plen);
	}
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_SPLICE_LOCKED */
/* When we receive funding_locked. */
u8 *towire_channeld_got_splice_locked(const tal_t *ctx, struct amount_sat funding_sats, s64 splice_amnt, const struct bitcoin_txid *locked_txid)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_SPLICE_LOCKED);
	towire_amount_sat(&p, funding_sats);
	towire_s64(&p, splice_amnt);
	towire_bitcoin_txid(&p, locked_txid);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_splice_locked(const void *p, struct amount_sat *funding_sats, s64 *splice_amnt, struct bitcoin_txid *locked_txid)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_SPLICE_LOCKED)
		return false;
 	*funding_sats = fromwire_amount_sat(&cursor, &plen);
 	*splice_amnt = fromwire_s64(&cursor, &plen);
 	fromwire_bitcoin_txid(&cursor, &plen, locked_txid);
	return cursor != NULL;
}

/* WIRE: CHANNELD_LOCAL_ANCHOR_INFO */
/* lightningd needs to track our anchor outputs on remote txs. */
/* This includes splices */
u8 *towire_channeld_local_anchor_info(const tal_t *ctx, u64 remote_commitnum, const struct local_anchor_info *anchors)
{
	u16 num_anchors = tal_count(anchors);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_LOCAL_ANCHOR_INFO);
	towire_u64(&p, remote_commitnum);
	towire_u16(&p, num_anchors);
	for (size_t i = 0; i < num_anchors; i++)
		towire_local_anchor_info(&p, anchors + i);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_local_anchor_info(const tal_t *ctx, const void *p, u64 *remote_commitnum, struct local_anchor_info **anchors)
{
	u16 num_anchors;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_LOCAL_ANCHOR_INFO)
		return false;
 	*remote_commitnum = fromwire_u64(&cursor, &plen);
 	num_anchors = fromwire_u16(&cursor, &plen);
 	// 2nd case anchors
	*anchors = num_anchors ? tal_arr(ctx, struct local_anchor_info, num_anchors) : NULL;
	for (size_t i = 0; i < num_anchors; i++)
		fromwire_local_anchor_info(&cursor, &plen, *anchors + i);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SENDING_COMMITSIG */
/* When we send a commitment_signed message */
u8 *towire_channeld_sending_commitsig(const tal_t *ctx, u64 commitnum, const struct penalty_base *pbase, const struct fee_states *fee_states, const struct height_states *blockheight_states, const struct changed_htlc *changed)
{
	u16 num_changed = tal_count(changed);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SENDING_COMMITSIG);
	towire_u64(&p, commitnum);
	if (!pbase)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_penalty_base(&p, pbase);
	}
	towire_fee_states(&p, fee_states);
	towire_height_states(&p, blockheight_states);
	/* SENT_ADD_COMMIT */
	towire_u16(&p, num_changed);
	for (size_t i = 0; i < num_changed; i++)
		towire_changed_htlc(&p, changed + i);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_sending_commitsig(const tal_t *ctx, const void *p, u64 *commitnum, struct penalty_base **pbase, struct fee_states **fee_states, struct height_states **blockheight_states, struct changed_htlc **changed)
{
	u16 num_changed;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SENDING_COMMITSIG)
		return false;
 	*commitnum = fromwire_u64(&cursor, &plen);
 	if (!fromwire_bool(&cursor, &plen))
		*pbase = NULL;
	else {
		*pbase = tal(ctx, struct penalty_base);
		fromwire_penalty_base(&cursor, &plen, *pbase);
	}
 	*fee_states = fromwire_fee_states(ctx, &cursor, &plen);
 	*blockheight_states = fromwire_height_states(ctx, &cursor, &plen);
 	/* SENT_ADD_COMMIT */
	num_changed = fromwire_u16(&cursor, &plen);
 	// 2nd case changed
	*changed = num_changed ? tal_arr(ctx, struct changed_htlc, num_changed) : NULL;
	for (size_t i = 0; i < num_changed; i++)
		fromwire_changed_htlc(&cursor, &plen, *changed + i);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SENDING_COMMITSIG_REPLY */
/* Wait for reply */
u8 *towire_channeld_sending_commitsig_reply(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SENDING_COMMITSIG_REPLY);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_sending_commitsig_reply(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SENDING_COMMITSIG_REPLY)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_COMMITSIG */
/* When we have a commitment_signed message */
u8 *towire_channeld_got_commitsig(const tal_t *ctx, u64 commitnum, const struct fee_states *fee_states, const struct height_states *blockheight_states, const struct bitcoin_signature *signature, const struct bitcoin_signature *htlc_signature, const struct added_htlc *added, const struct fulfilled_htlc *fulfilled, const struct failed_htlc **failed, const struct changed_htlc *changed, const struct bitcoin_tx *tx, const struct commitsig **inflight_commitsigs)
{
	u16 num_htlcs = tal_count(htlc_signature);
	u16 num_added = tal_count(added);
	u16 num_fulfilled = tal_count(fulfilled);
	u16 num_failed = tal_count(failed);
	u16 num_changed = tal_count(changed);
	u16 num_inflight_commitsigs = tal_count(inflight_commitsigs);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_COMMITSIG);
	towire_u64(&p, commitnum);
	towire_fee_states(&p, fee_states);
	towire_height_states(&p, blockheight_states);
	towire_bitcoin_signature(&p, signature);
	towire_u16(&p, num_htlcs);
	for (size_t i = 0; i < num_htlcs; i++)
		towire_bitcoin_signature(&p, htlc_signature + i);
	/* RCVD_ADD_COMMIT: we're now committed to their new offered HTLCs. */
	towire_u16(&p, num_added);
	for (size_t i = 0; i < num_added; i++)
		towire_added_htlc(&p, added + i);
	/* RCVD_REMOVE_COMMIT: we're now no longer committed to these HTLCs. */
	towire_u16(&p, num_fulfilled);
	for (size_t i = 0; i < num_fulfilled; i++)
		towire_fulfilled_htlc(&p, fulfilled + i);
	towire_u16(&p, num_failed);
	for (size_t i = 0; i < num_failed; i++)
		towire_failed_htlc(&p, failed[i]);
	/* RCVD_ADD_ACK_COMMIT */
	towire_u16(&p, num_changed);
	for (size_t i = 0; i < num_changed; i++)
		towire_changed_htlc(&p, changed + i);
	towire_bitcoin_tx(&p, tx);
	/* Inflight splice commitments */
	towire_u16(&p, num_inflight_commitsigs);
	for (size_t i = 0; i < num_inflight_commitsigs; i++)
		towire_commitsig(&p, inflight_commitsigs[i]);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_commitsig(const tal_t *ctx, const void *p, u64 *commitnum, struct fee_states **fee_states, struct height_states **blockheight_states, struct bitcoin_signature *signature, struct bitcoin_signature **htlc_signature, struct added_htlc **added, struct fulfilled_htlc **fulfilled, struct failed_htlc ***failed, struct changed_htlc **changed, struct bitcoin_tx **tx, struct commitsig ***inflight_commitsigs)
{
	u16 num_htlcs;
	u16 num_added;
	u16 num_fulfilled;
	u16 num_failed;
	u16 num_changed;
	u16 num_inflight_commitsigs;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_COMMITSIG)
		return false;
 	*commitnum = fromwire_u64(&cursor, &plen);
 	*fee_states = fromwire_fee_states(ctx, &cursor, &plen);
 	*blockheight_states = fromwire_height_states(ctx, &cursor, &plen);
 	fromwire_bitcoin_signature(&cursor, &plen, signature);
 	num_htlcs = fromwire_u16(&cursor, &plen);
 	// 2nd case htlc_signature
	*htlc_signature = num_htlcs ? tal_arr(ctx, struct bitcoin_signature, num_htlcs) : NULL;
	for (size_t i = 0; i < num_htlcs; i++)
		fromwire_bitcoin_signature(&cursor, &plen, *htlc_signature + i);
 	/* RCVD_ADD_COMMIT: we're now committed to their new offered HTLCs. */
	num_added = fromwire_u16(&cursor, &plen);
 	// 2nd case added
	*added = num_added ? tal_arr(ctx, struct added_htlc, num_added) : NULL;
	for (size_t i = 0; i < num_added; i++)
		fromwire_added_htlc(&cursor, &plen, *added + i);
 	/* RCVD_REMOVE_COMMIT: we're now no longer committed to these HTLCs. */
	num_fulfilled = fromwire_u16(&cursor, &plen);
 	// 2nd case fulfilled
	*fulfilled = num_fulfilled ? tal_arr(ctx, struct fulfilled_htlc, num_fulfilled) : NULL;
	for (size_t i = 0; i < num_fulfilled; i++)
		fromwire_fulfilled_htlc(&cursor, &plen, *fulfilled + i);
 	num_failed = fromwire_u16(&cursor, &plen);
 	// 2nd case failed
	*failed = num_failed ? tal_arr(ctx, struct failed_htlc *, num_failed) : NULL;
	for (size_t i = 0; i < num_failed; i++)
		(*failed)[i] = fromwire_failed_htlc(*failed, &cursor, &plen);
 	/* RCVD_ADD_ACK_COMMIT */
	num_changed = fromwire_u16(&cursor, &plen);
 	// 2nd case changed
	*changed = num_changed ? tal_arr(ctx, struct changed_htlc, num_changed) : NULL;
	for (size_t i = 0; i < num_changed; i++)
		fromwire_changed_htlc(&cursor, &plen, *changed + i);
 	*tx = fromwire_bitcoin_tx(ctx, &cursor, &plen);
 	/* Inflight splice commitments */
	num_inflight_commitsigs = fromwire_u16(&cursor, &plen);
 	// 2nd case inflight_commitsigs
	*inflight_commitsigs = num_inflight_commitsigs ? tal_arr(ctx, struct commitsig *, num_inflight_commitsigs) : NULL;
	for (size_t i = 0; i < num_inflight_commitsigs; i++)
		(*inflight_commitsigs)[i] = fromwire_commitsig(*inflight_commitsigs, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_COMMITSIG_REPLY */
/* Wait for reply */
u8 *towire_channeld_got_commitsig_reply(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_COMMITSIG_REPLY);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_commitsig_reply(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_COMMITSIG_REPLY)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_REVOKE */
u8 *towire_channeld_got_revoke(const tal_t *ctx, u64 revokenum, const struct secret *per_commitment_secret, const struct pubkey *next_per_commit_point, const struct fee_states *fee_states, const struct height_states *blockheight_states, const struct changed_htlc *changed, const struct penalty_base *pbase, const struct bitcoin_tx *penalty_tx)
{
	u16 num_changed = tal_count(changed);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_REVOKE);
	towire_u64(&p, revokenum);
	towire_secret(&p, per_commitment_secret);
	towire_pubkey(&p, next_per_commit_point);
	/* RCVD_ADD_ACK_REVOCATION */
	towire_fee_states(&p, fee_states);
	towire_height_states(&p, blockheight_states);
	towire_u16(&p, num_changed);
	for (size_t i = 0; i < num_changed; i++)
		towire_changed_htlc(&p, changed + i);
	if (!pbase)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_penalty_base(&p, pbase);
	}
	if (!penalty_tx)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_bitcoin_tx(&p, penalty_tx);
	}

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_revoke(const tal_t *ctx, const void *p, u64 *revokenum, struct secret *per_commitment_secret, struct pubkey *next_per_commit_point, struct fee_states **fee_states, struct height_states **blockheight_states, struct changed_htlc **changed, struct penalty_base **pbase, struct bitcoin_tx **penalty_tx)
{
	u16 num_changed;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_REVOKE)
		return false;
 	*revokenum = fromwire_u64(&cursor, &plen);
 	fromwire_secret(&cursor, &plen, per_commitment_secret);
 	fromwire_pubkey(&cursor, &plen, next_per_commit_point);
 	/* RCVD_ADD_ACK_REVOCATION */
	*fee_states = fromwire_fee_states(ctx, &cursor, &plen);
 	*blockheight_states = fromwire_height_states(ctx, &cursor, &plen);
 	num_changed = fromwire_u16(&cursor, &plen);
 	// 2nd case changed
	*changed = num_changed ? tal_arr(ctx, struct changed_htlc, num_changed) : NULL;
	for (size_t i = 0; i < num_changed; i++)
		fromwire_changed_htlc(&cursor, &plen, *changed + i);
 	if (!fromwire_bool(&cursor, &plen))
		*pbase = NULL;
	else {
		*pbase = tal(ctx, struct penalty_base);
		fromwire_penalty_base(&cursor, &plen, *pbase);
	}
 	if (!fromwire_bool(&cursor, &plen))
		*penalty_tx = NULL;
	else {
		*penalty_tx = fromwire_bitcoin_tx(ctx, &cursor, &plen);
	}
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_REVOKE_REPLY */
/* Wait for reply */
/* (eg. if we sent another commitment_signed */
u8 *towire_channeld_got_revoke_reply(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_REVOKE_REPLY);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_revoke_reply(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_REVOKE_REPLY)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_INIT */
/* master->channeld: hello */
u8 *towire_channeld_splice_init(const tal_t *ctx, const struct wally_psbt *psbt, s64 relative_amount, u32 feerate_per_kw, bool force_feerate, bool skip_stfu)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_INIT);
	towire_wally_psbt(&p, psbt);
	towire_s64(&p, relative_amount);
	towire_u32(&p, feerate_per_kw);
	towire_bool(&p, force_feerate);
	towire_bool(&p, skip_stfu);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_init(const tal_t *ctx, const void *p, struct wally_psbt **psbt, s64 *relative_amount, u32 *feerate_per_kw, bool *force_feerate, bool *skip_stfu)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_INIT)
		return false;
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
 	*relative_amount = fromwire_s64(&cursor, &plen);
 	*feerate_per_kw = fromwire_u32(&cursor, &plen);
 	*force_feerate = fromwire_bool(&cursor, &plen);
 	*skip_stfu = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_CONFIRMED_INIT */
/* channeld->master: hello */
u8 *towire_channeld_splice_confirmed_init(const tal_t *ctx, const struct wally_psbt *psbt)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_CONFIRMED_INIT);
	towire_wally_psbt(&p, psbt);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_confirmed_init(const tal_t *ctx, const void *p, struct wally_psbt **psbt)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_CONFIRMED_INIT)
		return false;
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_UPDATE */
/* master->channeld: Update an active splice */
u8 *towire_channeld_splice_update(const tal_t *ctx, const struct wally_psbt *psbt)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_UPDATE);
	towire_wally_psbt(&p, psbt);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_update(const tal_t *ctx, const void *p, struct wally_psbt **psbt)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_UPDATE)
		return false;
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_CONFIRMED_UPDATE */
/* channeld->master: Splice update complete */
u8 *towire_channeld_splice_confirmed_update(const tal_t *ctx, const struct wally_psbt *psbt, bool commitments_secured, bool signatures_secured)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_CONFIRMED_UPDATE);
	towire_wally_psbt(&p, psbt);
	towire_bool(&p, commitments_secured);
	towire_bool(&p, signatures_secured);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_confirmed_update(const tal_t *ctx, const void *p, struct wally_psbt **psbt, bool *commitments_secured, bool *signatures_secured)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_CONFIRMED_UPDATE)
		return false;
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
 	*commitments_secured = fromwire_bool(&cursor, &plen);
 	*signatures_secured = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_LOOKUP_TX */
/* channeld->master: Lookup a transaction */
u8 *towire_channeld_splice_lookup_tx(const tal_t *ctx, const struct bitcoin_txid *txid)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_LOOKUP_TX);
	towire_bitcoin_txid(&p, txid);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_lookup_tx(const void *p, struct bitcoin_txid *txid)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_LOOKUP_TX)
		return false;
 	fromwire_bitcoin_txid(&cursor, &plen, txid);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_LOOKUP_TX_RESULT */
/* master->channeld: Retrieved transaction */
u8 *towire_channeld_splice_lookup_tx_result(const tal_t *ctx, const struct bitcoin_tx *tx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_LOOKUP_TX_RESULT);
	towire_bitcoin_tx(&p, tx);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_lookup_tx_result(const tal_t *ctx, const void *p, struct bitcoin_tx **tx)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_LOOKUP_TX_RESULT)
		return false;
 	*tx = fromwire_bitcoin_tx(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_SIGNED */
/* master->channeld: User has signed psbt and it's ready to complete */
u8 *towire_channeld_splice_signed(const tal_t *ctx, const struct wally_psbt *psbt, bool force_sign_first)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_SIGNED);
	towire_wally_psbt(&p, psbt);
	towire_bool(&p, force_sign_first);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_signed(const tal_t *ctx, const void *p, struct wally_psbt **psbt, bool *force_sign_first)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_SIGNED)
		return false;
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
 	*force_sign_first = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_CONFIRMED_SIGNED */
/* channeld->master: Signed psbt is completed */
u8 *towire_channeld_splice_confirmed_signed(const tal_t *ctx, const struct bitcoin_tx *tx, u32 output_index)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_CONFIRMED_SIGNED);
	towire_bitcoin_tx(&p, tx);
	towire_u32(&p, output_index);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_confirmed_signed(const tal_t *ctx, const void *p, struct bitcoin_tx **tx, u32 *output_index)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_CONFIRMED_SIGNED)
		return false;
 	*tx = fromwire_bitcoin_tx(ctx, &cursor, &plen);
 	*output_index = fromwire_u32(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_SENDING_SIGS */
/* channeld->master: Splice signatures are about to be sent */
u8 *towire_channeld_splice_sending_sigs(const tal_t *ctx, const struct bitcoin_txid *tx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_SENDING_SIGS);
	towire_bitcoin_txid(&p, tx);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_sending_sigs(const void *p, struct bitcoin_txid *tx)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_SENDING_SIGS)
		return false;
 	fromwire_bitcoin_txid(&cursor, &plen, tx);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_FEERATE_ERROR */
/* channeld->master: A feerate error has occured */
u8 *towire_channeld_splice_feerate_error(const tal_t *ctx, struct amount_msat fee, bool too_high)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_FEERATE_ERROR);
	towire_amount_msat(&p, fee);
	towire_bool(&p, too_high);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_feerate_error(const void *p, struct amount_msat *fee, bool *too_high)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_FEERATE_ERROR)
		return false;
 	*fee = fromwire_amount_msat(&cursor, &plen);
 	*too_high = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_ADD_INFLIGHT */
/* channeld->master: Add an inflight to the DB */
u8 *towire_channeld_add_inflight(const tal_t *ctx, const struct pubkey *remote_funding, const struct bitcoin_txid *tx_id, u32 tx_outnum, u32 feerate, struct amount_sat satoshis, s64 splice_amount, const struct wally_psbt *psbt, bool i_am_initiator, bool force_sign_first)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_ADD_INFLIGHT);
	towire_pubkey(&p, remote_funding);
	towire_bitcoin_txid(&p, tx_id);
	towire_u32(&p, tx_outnum);
	towire_u32(&p, feerate);
	towire_amount_sat(&p, satoshis);
	towire_s64(&p, splice_amount);
	towire_wally_psbt(&p, psbt);
	towire_bool(&p, i_am_initiator);
	towire_bool(&p, force_sign_first);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_add_inflight(const tal_t *ctx, const void *p, struct pubkey *remote_funding, struct bitcoin_txid *tx_id, u32 *tx_outnum, u32 *feerate, struct amount_sat *satoshis, s64 *splice_amount, struct wally_psbt **psbt, bool *i_am_initiator, bool *force_sign_first)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_ADD_INFLIGHT)
		return false;
 	fromwire_pubkey(&cursor, &plen, remote_funding);
 	fromwire_bitcoin_txid(&cursor, &plen, tx_id);
 	*tx_outnum = fromwire_u32(&cursor, &plen);
 	*feerate = fromwire_u32(&cursor, &plen);
 	*satoshis = fromwire_amount_sat(&cursor, &plen);
 	*splice_amount = fromwire_s64(&cursor, &plen);
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
 	*i_am_initiator = fromwire_bool(&cursor, &plen);
 	*force_sign_first = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_INFLIGHT */
/* master->channeld: Inflight saved successfully */
u8 *towire_channeld_got_inflight(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_INFLIGHT);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_inflight(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_INFLIGHT)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_UPDATE_INFLIGHT */
/* channeld->master: Update inflight with sigs */
u8 *towire_channeld_update_inflight(const tal_t *ctx, const struct wally_psbt *psbt, const struct bitcoin_tx *last_tx, const struct bitcoin_signature *last_sig)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_UPDATE_INFLIGHT);
	towire_wally_psbt(&p, psbt);
	if (!last_tx)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_bitcoin_tx(&p, last_tx);
	}
	if (!last_sig)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_bitcoin_signature(&p, last_sig);
	}

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_update_inflight(const tal_t *ctx, const void *p, struct wally_psbt **psbt, struct bitcoin_tx **last_tx, struct bitcoin_signature **last_sig)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_UPDATE_INFLIGHT)
		return false;
 	*psbt = fromwire_wally_psbt(ctx, &cursor, &plen);
 	if (!fromwire_bool(&cursor, &plen))
		*last_tx = NULL;
	else {
		*last_tx = fromwire_bitcoin_tx(ctx, &cursor, &plen);
	}
 	if (!fromwire_bool(&cursor, &plen))
		*last_sig = NULL;
	else {
		*last_sig = tal(ctx, struct bitcoin_signature);
		fromwire_bitcoin_signature(&cursor, &plen, *last_sig);
	}
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_FUNDING_ERROR */
/* channeld->master: A funding error has occured */
u8 *towire_channeld_splice_funding_error(const tal_t *ctx, struct amount_msat funding, struct amount_msat req_funding, bool opener_error)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_FUNDING_ERROR);
	towire_amount_msat(&p, funding);
	towire_amount_msat(&p, req_funding);
	towire_bool(&p, opener_error);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_funding_error(const void *p, struct amount_msat *funding, struct amount_msat *req_funding, bool *opener_error)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_FUNDING_ERROR)
		return false;
 	*funding = fromwire_amount_msat(&cursor, &plen);
 	*req_funding = fromwire_amount_msat(&cursor, &plen);
 	*opener_error = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_STATE_ERROR */
/* channeld->master: A splice state error has occured */
u8 *towire_channeld_splice_state_error(const tal_t *ctx, const wirestring *state_error)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_STATE_ERROR);
	towire_wirestring(&p, state_error);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_state_error(const tal_t *ctx, const void *p, wirestring **state_error)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_STATE_ERROR)
		return false;
 	*state_error = fromwire_wirestring(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SPLICE_ABORT */
/* channeld->master: Peer rejected our splice */
u8 *towire_channeld_splice_abort(const tal_t *ctx, bool did_i_initiate, const struct bitcoin_outpoint *inflight_outpoint, const wirestring *reason)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SPLICE_ABORT);
	towire_bool(&p, did_i_initiate);
	if (!inflight_outpoint)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_bitcoin_outpoint(&p, inflight_outpoint);
	}
	towire_wirestring(&p, reason);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_splice_abort(const tal_t *ctx, const void *p, bool *did_i_initiate, struct bitcoin_outpoint **inflight_outpoint, wirestring **reason)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SPLICE_ABORT)
		return false;
 	*did_i_initiate = fromwire_bool(&cursor, &plen);
 	if (!fromwire_bool(&cursor, &plen))
		*inflight_outpoint = NULL;
	else {
		*inflight_outpoint = tal(ctx, struct bitcoin_outpoint);
		fromwire_bitcoin_outpoint(&cursor, &plen, *inflight_outpoint);
	}
 	*reason = fromwire_wirestring(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_STFU */
/* master->channeld: Please enter stfu mode */
u8 *towire_channeld_stfu(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_STFU);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_stfu(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_STFU)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_CONFIRMED_STFU */
/* channeld->master: Entered stfu result */
u8 *towire_channeld_confirmed_stfu(const tal_t *ctx, struct amount_msat available_funds)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_CONFIRMED_STFU);
	towire_amount_msat(&p, available_funds);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_confirmed_stfu(const void *p, struct amount_msat *available_funds)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_CONFIRMED_STFU)
		return false;
 	*available_funds = fromwire_amount_msat(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_ABORT */
/* master->channeld: Please enter perform tx_abort */
u8 *towire_channeld_abort(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_ABORT);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_abort(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_ABORT)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_SEND_SHUTDOWN */
/* Tell peer to shut down channel. */
u8 *towire_channeld_send_shutdown(const tal_t *ctx, u32 *final_index, const struct ext_key *final_ext_key, const u8 *shutdown_scriptpubkey, const struct bitcoin_outpoint *wrong_funding)
{
	u16 shutdown_len = tal_count(shutdown_scriptpubkey);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SEND_SHUTDOWN);
	if (!final_index)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_u32(&p, *final_index);
	}
	if (!final_ext_key)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_ext_key(&p, final_ext_key);
	}
	towire_u16(&p, shutdown_len);
	towire_u8_array(&p, shutdown_scriptpubkey, shutdown_len);
	if (!wrong_funding)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_bitcoin_outpoint(&p, wrong_funding);
	}

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_send_shutdown(const tal_t *ctx, const void *p, u32 **final_index, struct ext_key **final_ext_key, u8 **shutdown_scriptpubkey, struct bitcoin_outpoint **wrong_funding)
{
	u16 shutdown_len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SEND_SHUTDOWN)
		return false;
 	if (!fromwire_bool(&cursor, &plen))
		*final_index = NULL;
	else {
		*final_index = tal(ctx, u32);
		**final_index = fromwire_u32(&cursor, &plen);
	}
 	if (!fromwire_bool(&cursor, &plen))
		*final_ext_key = NULL;
	else {
		*final_ext_key = tal(ctx, struct ext_key);
		fromwire_ext_key(&cursor, &plen, *final_ext_key);
	}
 	shutdown_len = fromwire_u16(&cursor, &plen);
 	// 2nd case shutdown_scriptpubkey
	*shutdown_scriptpubkey = shutdown_len ? tal_arr(ctx, u8, shutdown_len) : NULL;
	fromwire_u8_array(&cursor, &plen, *shutdown_scriptpubkey, shutdown_len);
 	if (!fromwire_bool(&cursor, &plen))
		*wrong_funding = NULL;
	else {
		*wrong_funding = tal(ctx, struct bitcoin_outpoint);
		fromwire_bitcoin_outpoint(&cursor, &plen, *wrong_funding);
	}
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_SHUTDOWN */
/* Peer told us that channel is shutting down */
u8 *towire_channeld_got_shutdown(const tal_t *ctx, const u8 *scriptpubkey, const struct bitcoin_outpoint *wrong_funding)
{
	u16 scriptpubkey_len = tal_count(scriptpubkey);
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_SHUTDOWN);
	towire_u16(&p, scriptpubkey_len);
	towire_u8_array(&p, scriptpubkey, scriptpubkey_len);
	if (!wrong_funding)
		towire_bool(&p, false);
	else {
		towire_bool(&p, true);
		towire_bitcoin_outpoint(&p, wrong_funding);
	}

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_shutdown(const tal_t *ctx, const void *p, u8 **scriptpubkey, struct bitcoin_outpoint **wrong_funding)
{
	u16 scriptpubkey_len;

	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_SHUTDOWN)
		return false;
 	scriptpubkey_len = fromwire_u16(&cursor, &plen);
 	// 2nd case scriptpubkey
	*scriptpubkey = scriptpubkey_len ? tal_arr(ctx, u8, scriptpubkey_len) : NULL;
	fromwire_u8_array(&cursor, &plen, *scriptpubkey, scriptpubkey_len);
 	if (!fromwire_bool(&cursor, &plen))
		*wrong_funding = NULL;
	else {
		*wrong_funding = tal(ctx, struct bitcoin_outpoint);
		fromwire_bitcoin_outpoint(&cursor, &plen, *wrong_funding);
	}
	return cursor != NULL;
}

/* WIRE: CHANNELD_SHUTDOWN_COMPLETE */
/* Shutdown is complete */
u8 *towire_channeld_shutdown_complete(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SHUTDOWN_COMPLETE);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_shutdown_complete(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SHUTDOWN_COMPLETE)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_REENABLE_COMMIT */
/* Re-enable commit timer. */
u8 *towire_channeld_dev_reenable_commit(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_REENABLE_COMMIT);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_reenable_commit(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_REENABLE_COMMIT)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_REENABLE_COMMIT_REPLY */
u8 *towire_channeld_dev_reenable_commit_reply(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_REENABLE_COMMIT_REPLY);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_reenable_commit_reply(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_REENABLE_COMMIT_REPLY)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_FEERATES */
u8 *towire_channeld_feerates(const tal_t *ctx, u32 feerate, u32 min_feerate, u32 max_feerate, u32 penalty_feerate)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_FEERATES);
	towire_u32(&p, feerate);
	towire_u32(&p, min_feerate);
	towire_u32(&p, max_feerate);
	towire_u32(&p, penalty_feerate);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_feerates(const void *p, u32 *feerate, u32 *min_feerate, u32 *max_feerate, u32 *penalty_feerate)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_FEERATES)
		return false;
 	*feerate = fromwire_u32(&cursor, &plen);
 	*min_feerate = fromwire_u32(&cursor, &plen);
 	*max_feerate = fromwire_u32(&cursor, &plen);
 	*penalty_feerate = fromwire_u32(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_MEMLEAK */
/* master -> channeld: do you have a memleak? */
u8 *towire_channeld_dev_memleak(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_MEMLEAK);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_memleak(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_MEMLEAK)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_MEMLEAK_REPLY */
u8 *towire_channeld_dev_memleak_reply(const tal_t *ctx, bool leak)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_MEMLEAK_REPLY);
	towire_bool(&p, leak);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_memleak_reply(const void *p, bool *leak)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_MEMLEAK_REPLY)
		return false;
 	*leak = fromwire_bool(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_FAIL_FALLEN_BEHIND */
/* Peer presented proof it was from the future. */
u8 *towire_channeld_fail_fallen_behind(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_FAIL_FALLEN_BEHIND);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_fail_fallen_behind(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_FAIL_FALLEN_BEHIND)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_GOT_ANNOUNCEMENT */
/* When we receive announcement_signatures for channel announce */
u8 *towire_channeld_got_announcement(const tal_t *ctx, struct short_channel_id scid, const secp256k1_ecdsa_signature *remote_ann_node_sig, const secp256k1_ecdsa_signature *remote_ann_bitcoin_sig)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_GOT_ANNOUNCEMENT);
	towire_short_channel_id(&p, scid);
	towire_secp256k1_ecdsa_signature(&p, remote_ann_node_sig);
	towire_secp256k1_ecdsa_signature(&p, remote_ann_bitcoin_sig);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_got_announcement(const void *p, struct short_channel_id *scid, secp256k1_ecdsa_signature *remote_ann_node_sig, secp256k1_ecdsa_signature *remote_ann_bitcoin_sig)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_GOT_ANNOUNCEMENT)
		return false;
 	*scid = fromwire_short_channel_id(&cursor, &plen);
 	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, remote_ann_node_sig);
 	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, remote_ann_bitcoin_sig);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SEND_ERROR */
/* Ask channeld to send a error message. Used in forgetting channel case. */
u8 *towire_channeld_send_error(const tal_t *ctx, const wirestring *reason)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SEND_ERROR);
	towire_wirestring(&p, reason);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_send_error(const tal_t *ctx, const void *p, wirestring **reason)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SEND_ERROR)
		return false;
 	*reason = fromwire_wirestring(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_SEND_ERROR_REPLY */
/* Tell master channeld has sent the error message. */
u8 *towire_channeld_send_error_reply(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_SEND_ERROR_REPLY);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_send_error_reply(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_SEND_ERROR_REPLY)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_QUIESCE */
/* Ask channeld to quiesce. */
u8 *towire_channeld_dev_quiesce(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_QUIESCE);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_quiesce(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_QUIESCE)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_QUIESCE_REPLY */
u8 *towire_channeld_dev_quiesce_reply(const tal_t *ctx)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_QUIESCE_REPLY);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_quiesce_reply(const void *p)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_QUIESCE_REPLY)
		return false;
	return cursor != NULL;
}

/* WIRE: CHANNELD_UPGRADED */
/* Tell master we're upgrading the commitment tx. */
u8 *towire_channeld_upgraded(const tal_t *ctx, const struct channel_type *new_type)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_UPGRADED);
	towire_channel_type(&p, new_type);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_upgraded(const tal_t *ctx, const void *p, struct channel_type **new_type)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_UPGRADED)
		return false;
 	*new_type = fromwire_channel_type(ctx, &cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_BLOCKHEIGHT */
/* Tell peer about our latest and greatest blockheight. */
u8 *towire_channeld_blockheight(const tal_t *ctx, u32 blockheight)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_BLOCKHEIGHT);
	towire_u32(&p, blockheight);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_blockheight(const void *p, u32 *blockheight)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_BLOCKHEIGHT)
		return false;
 	*blockheight = fromwire_u32(&cursor, &plen);
	return cursor != NULL;
}

/* WIRE: CHANNELD_DEV_PEER_SHACHAIN */
/* Tell channeld about peer's shachain seed. */
u8 *towire_channeld_dev_peer_shachain(const tal_t *ctx, const struct sha256 *seed)
{
	u8 *p = tal_arr(ctx, u8, 0);

	towire_u16(&p, WIRE_CHANNELD_DEV_PEER_SHACHAIN);
	towire_sha256(&p, seed);

	return memcheck(p, tal_count(p));
}
bool fromwire_channeld_dev_peer_shachain(const void *p, struct sha256 *seed)
{
	const u8 *cursor = p;
	size_t plen = tal_count(p);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNELD_DEV_PEER_SHACHAIN)
		return false;
 	fromwire_sha256(&cursor, &plen, seed);
	return cursor != NULL;
}
// SHA256STAMP:239463a994bc62b05c4f4b866c5d1e22fff3479b2b5a9f1e4e9a3e6cd426d4e7
