/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
/* Original template can be found at tools/gen/header_template */

#ifndef LIGHTNING_CHANNELD_CHANNELD_WIREGEN_H
#define LIGHTNING_CHANNELD_CHANNELD_WIREGEN_H
#include <ccan/tal/tal.h>
#include <wire/tlvstream.h>
#include <wire/wire.h>
#include <bitcoin/psbt.h>
#include <bitcoin/tx.h>
#include <channeld/inflight.h>
#include <common/bip32.h>
#include <common/blockheight_states.h>
#include <common/cryptomsg.h>
#include <common/channel_config.h>
#include <common/channel_id.h>
#include <common/channel_type.h>
#include <common/derive_basepoints.h>
#include <common/features.h>
#include <common/fee_states.h>
#include <wire/peer_wire.h>
#include <bitcoin/preimage.h>
#include <common/penalty_base.h>
#include <common/htlc_wire.h>
#include <wally_bip32.h>

enum channeld_wire {
        /*  Begin!  (passes gossipd-client fd) */
        WIRE_CHANNELD_INIT = 1000,
        /*  channeld->lightningd: successfully negotated reestablishment. */
        WIRE_CHANNELD_REESTABLISHED = 1101,
        /*  master->channeld funding hit new depth(funding locked if >= lock depth) */
        /*  short_channel_id != NULL once we have 3+ confirmations */
        WIRE_CHANNELD_FUNDING_DEPTH = 1002,
        /*  Tell channel to offer this htlc */
        WIRE_CHANNELD_OFFER_HTLC = 1004,
        /*  Reply; synchronous since IDs have to increment. */
        WIRE_CHANNELD_OFFER_HTLC_REPLY = 1104,
        /*  Main daemon found out the preimage for an HTLC */
        WIRE_CHANNELD_FULFILL_HTLC = 1005,
        /*  Main daemon says HTLC failed */
        WIRE_CHANNELD_FAIL_HTLC = 1006,
        /*  When we receive channel_ready. */
        WIRE_CHANNELD_GOT_CHANNEL_READY = 1019,
        /*  When we receive funding_locked. */
        WIRE_CHANNELD_GOT_SPLICE_LOCKED = 1119,
        /*  lightningd needs to track our anchor outputs on remote txs. */
        /*  This includes splices */
        WIRE_CHANNELD_LOCAL_ANCHOR_INFO = 1003,
        /*  When we send a commitment_signed message */
        WIRE_CHANNELD_SENDING_COMMITSIG = 1020,
        /*  Wait for reply */
        WIRE_CHANNELD_SENDING_COMMITSIG_REPLY = 1120,
        /*  When we have a commitment_signed message */
        WIRE_CHANNELD_GOT_COMMITSIG = 1021,
        /*  Wait for reply */
        WIRE_CHANNELD_GOT_COMMITSIG_REPLY = 1121,
        WIRE_CHANNELD_GOT_REVOKE = 1022,
        /*  Wait for reply */
        /*  (eg. if we sent another commitment_signed */
        WIRE_CHANNELD_GOT_REVOKE_REPLY = 1122,
        /*  master->channeld: hello */
        WIRE_CHANNELD_SPLICE_INIT = 7204,
        /*  channeld->master: hello */
        WIRE_CHANNELD_SPLICE_CONFIRMED_INIT = 7205,
        /*  master->channeld: Update an active splice */
        WIRE_CHANNELD_SPLICE_UPDATE = 7206,
        /*  channeld->master: Splice update complete */
        WIRE_CHANNELD_SPLICE_CONFIRMED_UPDATE = 7207,
        /*  channeld->master: Lookup a transaction */
        WIRE_CHANNELD_SPLICE_LOOKUP_TX = 7208,
        /*  master->channeld: Retrieved transaction */
        WIRE_CHANNELD_SPLICE_LOOKUP_TX_RESULT = 7209,
        /*  master->channeld: User has signed psbt and it's ready to complete */
        WIRE_CHANNELD_SPLICE_SIGNED = 7212,
        /*  channeld->master: Signed psbt is completed */
        WIRE_CHANNELD_SPLICE_CONFIRMED_SIGNED = 7213,
        /*  channeld->master: Splice signatures are about to be sent */
        WIRE_CHANNELD_SPLICE_SENDING_SIGS = 7214,
        /*  channeld->master: A feerate error has occured */
        WIRE_CHANNELD_SPLICE_FEERATE_ERROR = 7215,
        /*  channeld->master: Add an inflight to the DB */
        WIRE_CHANNELD_ADD_INFLIGHT = 7216,
        /*  master->channeld: Inflight saved successfully */
        WIRE_CHANNELD_GOT_INFLIGHT = 7217,
        /*  channeld->master: Update inflight with sigs */
        WIRE_CHANNELD_UPDATE_INFLIGHT = 7219,
        /*  channeld->master: A funding error has occured */
        WIRE_CHANNELD_SPLICE_FUNDING_ERROR = 7220,
        /*  channeld->master: A splice state error has occured */
        WIRE_CHANNELD_SPLICE_STATE_ERROR = 7221,
        /*  channeld->master: Peer rejected our splice */
        WIRE_CHANNELD_SPLICE_ABORT = 7223,
        /*  master->channeld: Please enter stfu mode */
        WIRE_CHANNELD_STFU = 7224,
        /*  channeld->master: Entered stfu result */
        WIRE_CHANNELD_CONFIRMED_STFU = 7225,
        /*  master->channeld: Please enter perform tx_abort */
        WIRE_CHANNELD_ABORT = 7226,
        /*  Tell peer to shut down channel. */
        WIRE_CHANNELD_SEND_SHUTDOWN = 1023,
        /*  Peer told us that channel is shutting down */
        WIRE_CHANNELD_GOT_SHUTDOWN = 1024,
        /*  Shutdown is complete */
        WIRE_CHANNELD_SHUTDOWN_COMPLETE = 1025,
        /*  Re-enable commit timer. */
        WIRE_CHANNELD_DEV_REENABLE_COMMIT = 1026,
        WIRE_CHANNELD_DEV_REENABLE_COMMIT_REPLY = 1126,
        WIRE_CHANNELD_FEERATES = 1027,
        /*  master -> channeld: do you have a memleak? */
        WIRE_CHANNELD_DEV_MEMLEAK = 1033,
        WIRE_CHANNELD_DEV_MEMLEAK_REPLY = 1133,
        /*  Peer presented proof it was from the future. */
        WIRE_CHANNELD_FAIL_FALLEN_BEHIND = 1028,
        /*  When we receive announcement_signatures for channel announce */
        WIRE_CHANNELD_GOT_ANNOUNCEMENT = 1017,
        /*  Ask channeld to send a error message. Used in forgetting channel case. */
        WIRE_CHANNELD_SEND_ERROR = 1008,
        /*  Tell master channeld has sent the error message. */
        WIRE_CHANNELD_SEND_ERROR_REPLY = 1108,
        /*  Ask channeld to quiesce. */
        WIRE_CHANNELD_DEV_QUIESCE = 1009,
        WIRE_CHANNELD_DEV_QUIESCE_REPLY = 1109,
        /*  Tell master we're upgrading the commitment tx. */
        WIRE_CHANNELD_UPGRADED = 1011,
        /*  Tell peer about our latest and greatest blockheight. */
        WIRE_CHANNELD_BLOCKHEIGHT = 1012,
        /*  Tell channeld about peer's shachain seed. */
        WIRE_CHANNELD_DEV_PEER_SHACHAIN = 1013,
};

const char *channeld_wire_name(int e);

/**
 * Determine whether a given message type is defined as a message.
 *
 * Returns true if the message type is part of the message definitions we have
 * generated parsers for, false if it is a custom message that cannot be
 * handled internally.
 */
bool channeld_wire_is_defined(u16 type);


struct local_anchor_info {
        u32 commitment_weight;
        struct amount_sat commitment_fee;
        struct bitcoin_outpoint anchor_point;
};
struct commitsig {
        struct bitcoin_tx *tx;
        struct bitcoin_signature commit_signature;
        struct bitcoin_signature *htlc_signatures;
};

/* WIRE: CHANNELD_INIT */
/*  Begin!  (passes gossipd-client fd) */
u8 *towire_channeld_init(const tal_t *ctx, const struct chainparams *chainparams, const struct feature_set *our_features, const u32 *hsm_capabilities, const struct channel_id *channel_id, const struct bitcoin_outpoint *funding, struct amount_sat funding_satoshi, u32 minimum_depth, u32 our_blockheight, const struct height_states *blockheight_states, u32 lease_expiry, const struct channel_config *our_config, const struct channel_config *their_config, const struct fee_states *fee_states, u32 feerate_min, u32 feerate_max, u32 feerate_penalty, const struct bitcoin_signature *first_commit_sig, const struct pubkey *remote_fundingkey, const struct basepoints *remote_basepoints, const struct pubkey *remote_per_commit, const struct pubkey *old_remote_per_commit, enum side opener, struct amount_msat local_msatoshi, const struct basepoints *our_basepoints, const struct pubkey *our_funding_pubkey, u32 commit_msec, bool last_was_revoke, const struct changed_htlc *last_sent_commit, u64 next_index_local, u64 next_index_remote, u64 revocations_received, u64 next_htlc_id, const struct existing_htlc **htlcs, bool local_channel_ready, bool remote_channel_ready, struct short_channel_id funding_short_id, bool reestablish, bool send_shutdown, bool remote_shutdown_received, u32 final_index, const struct ext_key *final_ext_key, const u8 *final_scriptpubkey, u8 flags, const u8 *init_peer_pkt, const struct secret *last_remote_secret, const u8 *their_features, const u8 *upfront_shutdown_script, const struct channel_type *desired_type, u32 *dev_disable_commit, const struct penalty_base *pbases, bool reestablish_only, bool experimental_upgrade, const struct inflight **inflights, struct short_channel_id scid_alias);
bool fromwire_channeld_init(const tal_t *ctx, const void *p, const struct chainparams **chainparams, struct feature_set **our_features, u32 **hsm_capabilities, struct channel_id *channel_id, struct bitcoin_outpoint *funding, struct amount_sat *funding_satoshi, u32 *minimum_depth, u32 *our_blockheight, struct height_states **blockheight_states, u32 *lease_expiry, struct channel_config *our_config, struct channel_config *their_config, struct fee_states **fee_states, u32 *feerate_min, u32 *feerate_max, u32 *feerate_penalty, struct bitcoin_signature *first_commit_sig, struct pubkey *remote_fundingkey, struct basepoints *remote_basepoints, struct pubkey *remote_per_commit, struct pubkey *old_remote_per_commit, enum side *opener, struct amount_msat *local_msatoshi, struct basepoints *our_basepoints, struct pubkey *our_funding_pubkey, u32 *commit_msec, bool *last_was_revoke, struct changed_htlc **last_sent_commit, u64 *next_index_local, u64 *next_index_remote, u64 *revocations_received, u64 *next_htlc_id, struct existing_htlc ***htlcs, bool *local_channel_ready, bool *remote_channel_ready, struct short_channel_id *funding_short_id, bool *reestablish, bool *send_shutdown, bool *remote_shutdown_received, u32 *final_index, struct ext_key *final_ext_key, u8 **final_scriptpubkey, u8 *flags, u8 **init_peer_pkt, struct secret *last_remote_secret, u8 **their_features, u8 **upfront_shutdown_script, struct channel_type **desired_type, u32 **dev_disable_commit, struct penalty_base **pbases, bool *reestablish_only, bool *experimental_upgrade, struct inflight ***inflights, struct short_channel_id *scid_alias);

/* WIRE: CHANNELD_REESTABLISHED */
/*  channeld->lightningd: successfully negotated reestablishment. */
u8 *towire_channeld_reestablished(const tal_t *ctx);
bool fromwire_channeld_reestablished(const void *p);

/* WIRE: CHANNELD_FUNDING_DEPTH */
/*  master->channeld funding hit new depth(funding locked if >= lock depth) */
/*  short_channel_id != NULL once we have 3+ confirmations */
u8 *towire_channeld_funding_depth(const tal_t *ctx, struct short_channel_id *short_channel_id, u32 depth, bool splicing, const struct bitcoin_txid *txid);
bool fromwire_channeld_funding_depth(const tal_t *ctx, const void *p, struct short_channel_id **short_channel_id, u32 *depth, bool *splicing, struct bitcoin_txid *txid);

/* WIRE: CHANNELD_OFFER_HTLC */
/*  Tell channel to offer this htlc */
u8 *towire_channeld_offer_htlc(const tal_t *ctx, struct amount_msat amount_msat, u32 cltv_expiry, const struct sha256 *payment_hash, const u8 onion_routing_packet[1366], const struct pubkey *path_key);
bool fromwire_channeld_offer_htlc(const tal_t *ctx, const void *p, struct amount_msat *amount_msat, u32 *cltv_expiry, struct sha256 *payment_hash, u8 onion_routing_packet[1366], struct pubkey **path_key);

/* WIRE: CHANNELD_OFFER_HTLC_REPLY */
/*  Reply; synchronous since IDs have to increment. */
u8 *towire_channeld_offer_htlc_reply(const tal_t *ctx, u64 id, const u8 *failuremsg, const wirestring *failurestr);
bool fromwire_channeld_offer_htlc_reply(const tal_t *ctx, const void *p, u64 *id, u8 **failuremsg, wirestring **failurestr);

/* WIRE: CHANNELD_FULFILL_HTLC */
/*  Main daemon found out the preimage for an HTLC */
u8 *towire_channeld_fulfill_htlc(const tal_t *ctx, const struct fulfilled_htlc *fulfilled_htlc);
bool fromwire_channeld_fulfill_htlc(const void *p, struct fulfilled_htlc *fulfilled_htlc);

/* WIRE: CHANNELD_FAIL_HTLC */
/*  Main daemon says HTLC failed */
u8 *towire_channeld_fail_htlc(const tal_t *ctx, const struct failed_htlc *failed_htlc);
bool fromwire_channeld_fail_htlc(const tal_t *ctx, const void *p, struct failed_htlc **failed_htlc);

/* WIRE: CHANNELD_GOT_CHANNEL_READY */
/*  When we receive channel_ready. */
u8 *towire_channeld_got_channel_ready(const tal_t *ctx, const struct pubkey *next_per_commit_point, struct short_channel_id *alias);
bool fromwire_channeld_got_channel_ready(const tal_t *ctx, const void *p, struct pubkey *next_per_commit_point, struct short_channel_id **alias);

/* WIRE: CHANNELD_GOT_SPLICE_LOCKED */
/*  When we receive funding_locked. */
u8 *towire_channeld_got_splice_locked(const tal_t *ctx, struct amount_sat funding_sats, s64 splice_amnt, const struct bitcoin_txid *locked_txid);
bool fromwire_channeld_got_splice_locked(const void *p, struct amount_sat *funding_sats, s64 *splice_amnt, struct bitcoin_txid *locked_txid);

/* WIRE: CHANNELD_LOCAL_ANCHOR_INFO */
/*  lightningd needs to track our anchor outputs on remote txs. */
/*  This includes splices */
u8 *towire_channeld_local_anchor_info(const tal_t *ctx, u64 remote_commitnum, const struct local_anchor_info *anchors);
bool fromwire_channeld_local_anchor_info(const tal_t *ctx, const void *p, u64 *remote_commitnum, struct local_anchor_info **anchors);

/* WIRE: CHANNELD_SENDING_COMMITSIG */
/*  When we send a commitment_signed message */
u8 *towire_channeld_sending_commitsig(const tal_t *ctx, u64 commitnum, const struct penalty_base *pbase, const struct fee_states *fee_states, const struct height_states *blockheight_states, const struct changed_htlc *changed);
bool fromwire_channeld_sending_commitsig(const tal_t *ctx, const void *p, u64 *commitnum, struct penalty_base **pbase, struct fee_states **fee_states, struct height_states **blockheight_states, struct changed_htlc **changed);

/* WIRE: CHANNELD_SENDING_COMMITSIG_REPLY */
/*  Wait for reply */
u8 *towire_channeld_sending_commitsig_reply(const tal_t *ctx);
bool fromwire_channeld_sending_commitsig_reply(const void *p);

/* WIRE: CHANNELD_GOT_COMMITSIG */
/*  When we have a commitment_signed message */
u8 *towire_channeld_got_commitsig(const tal_t *ctx, u64 commitnum, const struct fee_states *fee_states, const struct height_states *blockheight_states, const struct bitcoin_signature *signature, const struct bitcoin_signature *htlc_signature, const struct added_htlc *added, const struct fulfilled_htlc *fulfilled, const struct failed_htlc **failed, const struct changed_htlc *changed, const struct bitcoin_tx *tx, const struct commitsig **inflight_commitsigs);
bool fromwire_channeld_got_commitsig(const tal_t *ctx, const void *p, u64 *commitnum, struct fee_states **fee_states, struct height_states **blockheight_states, struct bitcoin_signature *signature, struct bitcoin_signature **htlc_signature, struct added_htlc **added, struct fulfilled_htlc **fulfilled, struct failed_htlc ***failed, struct changed_htlc **changed, struct bitcoin_tx **tx, struct commitsig ***inflight_commitsigs);

/* WIRE: CHANNELD_GOT_COMMITSIG_REPLY */
/*  Wait for reply */
u8 *towire_channeld_got_commitsig_reply(const tal_t *ctx);
bool fromwire_channeld_got_commitsig_reply(const void *p);

/* WIRE: CHANNELD_GOT_REVOKE */
u8 *towire_channeld_got_revoke(const tal_t *ctx, u64 revokenum, const struct secret *per_commitment_secret, const struct pubkey *next_per_commit_point, const struct fee_states *fee_states, const struct height_states *blockheight_states, const struct changed_htlc *changed, const struct penalty_base *pbase, const struct bitcoin_tx *penalty_tx);
bool fromwire_channeld_got_revoke(const tal_t *ctx, const void *p, u64 *revokenum, struct secret *per_commitment_secret, struct pubkey *next_per_commit_point, struct fee_states **fee_states, struct height_states **blockheight_states, struct changed_htlc **changed, struct penalty_base **pbase, struct bitcoin_tx **penalty_tx);

/* WIRE: CHANNELD_GOT_REVOKE_REPLY */
/*  Wait for reply */
/*  (eg. if we sent another commitment_signed */
u8 *towire_channeld_got_revoke_reply(const tal_t *ctx);
bool fromwire_channeld_got_revoke_reply(const void *p);

/* WIRE: CHANNELD_SPLICE_INIT */
/*  master->channeld: hello */
u8 *towire_channeld_splice_init(const tal_t *ctx, const struct wally_psbt *psbt, s64 relative_amount, u32 feerate_per_kw, bool force_feerate, bool skip_stfu);
bool fromwire_channeld_splice_init(const tal_t *ctx, const void *p, struct wally_psbt **psbt, s64 *relative_amount, u32 *feerate_per_kw, bool *force_feerate, bool *skip_stfu);

/* WIRE: CHANNELD_SPLICE_CONFIRMED_INIT */
/*  channeld->master: hello */
u8 *towire_channeld_splice_confirmed_init(const tal_t *ctx, const struct wally_psbt *psbt);
bool fromwire_channeld_splice_confirmed_init(const tal_t *ctx, const void *p, struct wally_psbt **psbt);

/* WIRE: CHANNELD_SPLICE_UPDATE */
/*  master->channeld: Update an active splice */
u8 *towire_channeld_splice_update(const tal_t *ctx, const struct wally_psbt *psbt);
bool fromwire_channeld_splice_update(const tal_t *ctx, const void *p, struct wally_psbt **psbt);

/* WIRE: CHANNELD_SPLICE_CONFIRMED_UPDATE */
/*  channeld->master: Splice update complete */
u8 *towire_channeld_splice_confirmed_update(const tal_t *ctx, const struct wally_psbt *psbt, bool commitments_secured, bool signatures_secured);
bool fromwire_channeld_splice_confirmed_update(const tal_t *ctx, const void *p, struct wally_psbt **psbt, bool *commitments_secured, bool *signatures_secured);

/* WIRE: CHANNELD_SPLICE_LOOKUP_TX */
/*  channeld->master: Lookup a transaction */
u8 *towire_channeld_splice_lookup_tx(const tal_t *ctx, const struct bitcoin_txid *txid);
bool fromwire_channeld_splice_lookup_tx(const void *p, struct bitcoin_txid *txid);

/* WIRE: CHANNELD_SPLICE_LOOKUP_TX_RESULT */
/*  master->channeld: Retrieved transaction */
u8 *towire_channeld_splice_lookup_tx_result(const tal_t *ctx, const struct bitcoin_tx *tx);
bool fromwire_channeld_splice_lookup_tx_result(const tal_t *ctx, const void *p, struct bitcoin_tx **tx);

/* WIRE: CHANNELD_SPLICE_SIGNED */
/*  master->channeld: User has signed psbt and it's ready to complete */
u8 *towire_channeld_splice_signed(const tal_t *ctx, const struct wally_psbt *psbt, bool force_sign_first);
bool fromwire_channeld_splice_signed(const tal_t *ctx, const void *p, struct wally_psbt **psbt, bool *force_sign_first);

/* WIRE: CHANNELD_SPLICE_CONFIRMED_SIGNED */
/*  channeld->master: Signed psbt is completed */
u8 *towire_channeld_splice_confirmed_signed(const tal_t *ctx, const struct bitcoin_tx *tx, u32 output_index);
bool fromwire_channeld_splice_confirmed_signed(const tal_t *ctx, const void *p, struct bitcoin_tx **tx, u32 *output_index);

/* WIRE: CHANNELD_SPLICE_SENDING_SIGS */
/*  channeld->master: Splice signatures are about to be sent */
u8 *towire_channeld_splice_sending_sigs(const tal_t *ctx, const struct bitcoin_txid *tx);
bool fromwire_channeld_splice_sending_sigs(const void *p, struct bitcoin_txid *tx);

/* WIRE: CHANNELD_SPLICE_FEERATE_ERROR */
/*  channeld->master: A feerate error has occured */
u8 *towire_channeld_splice_feerate_error(const tal_t *ctx, struct amount_msat fee, bool too_high);
bool fromwire_channeld_splice_feerate_error(const void *p, struct amount_msat *fee, bool *too_high);

/* WIRE: CHANNELD_ADD_INFLIGHT */
/*  channeld->master: Add an inflight to the DB */
u8 *towire_channeld_add_inflight(const tal_t *ctx, const struct pubkey *remote_funding, const struct bitcoin_txid *tx_id, u32 tx_outnum, u32 feerate, struct amount_sat satoshis, s64 splice_amount, const struct wally_psbt *psbt, bool i_am_initiator, bool force_sign_first);
bool fromwire_channeld_add_inflight(const tal_t *ctx, const void *p, struct pubkey *remote_funding, struct bitcoin_txid *tx_id, u32 *tx_outnum, u32 *feerate, struct amount_sat *satoshis, s64 *splice_amount, struct wally_psbt **psbt, bool *i_am_initiator, bool *force_sign_first);

/* WIRE: CHANNELD_GOT_INFLIGHT */
/*  master->channeld: Inflight saved successfully */
u8 *towire_channeld_got_inflight(const tal_t *ctx);
bool fromwire_channeld_got_inflight(const void *p);

/* WIRE: CHANNELD_UPDATE_INFLIGHT */
/*  channeld->master: Update inflight with sigs */
u8 *towire_channeld_update_inflight(const tal_t *ctx, const struct wally_psbt *psbt, const struct bitcoin_tx *last_tx, const struct bitcoin_signature *last_sig);
bool fromwire_channeld_update_inflight(const tal_t *ctx, const void *p, struct wally_psbt **psbt, struct bitcoin_tx **last_tx, struct bitcoin_signature **last_sig);

/* WIRE: CHANNELD_SPLICE_FUNDING_ERROR */
/*  channeld->master: A funding error has occured */
u8 *towire_channeld_splice_funding_error(const tal_t *ctx, struct amount_msat funding, struct amount_msat req_funding, bool opener_error);
bool fromwire_channeld_splice_funding_error(const void *p, struct amount_msat *funding, struct amount_msat *req_funding, bool *opener_error);

/* WIRE: CHANNELD_SPLICE_STATE_ERROR */
/*  channeld->master: A splice state error has occured */
u8 *towire_channeld_splice_state_error(const tal_t *ctx, const wirestring *state_error);
bool fromwire_channeld_splice_state_error(const tal_t *ctx, const void *p, wirestring **state_error);

/* WIRE: CHANNELD_SPLICE_ABORT */
/*  channeld->master: Peer rejected our splice */
u8 *towire_channeld_splice_abort(const tal_t *ctx, bool did_i_initiate, const struct bitcoin_outpoint *inflight_outpoint, const wirestring *reason);
bool fromwire_channeld_splice_abort(const tal_t *ctx, const void *p, bool *did_i_initiate, struct bitcoin_outpoint **inflight_outpoint, wirestring **reason);

/* WIRE: CHANNELD_STFU */
/*  master->channeld: Please enter stfu mode */
u8 *towire_channeld_stfu(const tal_t *ctx);
bool fromwire_channeld_stfu(const void *p);

/* WIRE: CHANNELD_CONFIRMED_STFU */
/*  channeld->master: Entered stfu result */
u8 *towire_channeld_confirmed_stfu(const tal_t *ctx, struct amount_msat available_funds);
bool fromwire_channeld_confirmed_stfu(const void *p, struct amount_msat *available_funds);

/* WIRE: CHANNELD_ABORT */
/*  master->channeld: Please enter perform tx_abort */
u8 *towire_channeld_abort(const tal_t *ctx);
bool fromwire_channeld_abort(const void *p);

/* WIRE: CHANNELD_SEND_SHUTDOWN */
/*  Tell peer to shut down channel. */
u8 *towire_channeld_send_shutdown(const tal_t *ctx, u32 *final_index, const struct ext_key *final_ext_key, const u8 *shutdown_scriptpubkey, const struct bitcoin_outpoint *wrong_funding);
bool fromwire_channeld_send_shutdown(const tal_t *ctx, const void *p, u32 **final_index, struct ext_key **final_ext_key, u8 **shutdown_scriptpubkey, struct bitcoin_outpoint **wrong_funding);

/* WIRE: CHANNELD_GOT_SHUTDOWN */
/*  Peer told us that channel is shutting down */
u8 *towire_channeld_got_shutdown(const tal_t *ctx, const u8 *scriptpubkey, const struct bitcoin_outpoint *wrong_funding);
bool fromwire_channeld_got_shutdown(const tal_t *ctx, const void *p, u8 **scriptpubkey, struct bitcoin_outpoint **wrong_funding);

/* WIRE: CHANNELD_SHUTDOWN_COMPLETE */
/*  Shutdown is complete */
u8 *towire_channeld_shutdown_complete(const tal_t *ctx);
bool fromwire_channeld_shutdown_complete(const void *p);

/* WIRE: CHANNELD_DEV_REENABLE_COMMIT */
/*  Re-enable commit timer. */
u8 *towire_channeld_dev_reenable_commit(const tal_t *ctx);
bool fromwire_channeld_dev_reenable_commit(const void *p);

/* WIRE: CHANNELD_DEV_REENABLE_COMMIT_REPLY */
u8 *towire_channeld_dev_reenable_commit_reply(const tal_t *ctx);
bool fromwire_channeld_dev_reenable_commit_reply(const void *p);

/* WIRE: CHANNELD_FEERATES */
u8 *towire_channeld_feerates(const tal_t *ctx, u32 feerate, u32 min_feerate, u32 max_feerate, u32 penalty_feerate);
bool fromwire_channeld_feerates(const void *p, u32 *feerate, u32 *min_feerate, u32 *max_feerate, u32 *penalty_feerate);

/* WIRE: CHANNELD_DEV_MEMLEAK */
/*  master -> channeld: do you have a memleak? */
u8 *towire_channeld_dev_memleak(const tal_t *ctx);
bool fromwire_channeld_dev_memleak(const void *p);

/* WIRE: CHANNELD_DEV_MEMLEAK_REPLY */
u8 *towire_channeld_dev_memleak_reply(const tal_t *ctx, bool leak);
bool fromwire_channeld_dev_memleak_reply(const void *p, bool *leak);

/* WIRE: CHANNELD_FAIL_FALLEN_BEHIND */
/*  Peer presented proof it was from the future. */
u8 *towire_channeld_fail_fallen_behind(const tal_t *ctx);
bool fromwire_channeld_fail_fallen_behind(const void *p);

/* WIRE: CHANNELD_GOT_ANNOUNCEMENT */
/*  When we receive announcement_signatures for channel announce */
u8 *towire_channeld_got_announcement(const tal_t *ctx, struct short_channel_id scid, const secp256k1_ecdsa_signature *remote_ann_node_sig, const secp256k1_ecdsa_signature *remote_ann_bitcoin_sig);
bool fromwire_channeld_got_announcement(const void *p, struct short_channel_id *scid, secp256k1_ecdsa_signature *remote_ann_node_sig, secp256k1_ecdsa_signature *remote_ann_bitcoin_sig);

/* WIRE: CHANNELD_SEND_ERROR */
/*  Ask channeld to send a error message. Used in forgetting channel case. */
u8 *towire_channeld_send_error(const tal_t *ctx, const wirestring *reason);
bool fromwire_channeld_send_error(const tal_t *ctx, const void *p, wirestring **reason);

/* WIRE: CHANNELD_SEND_ERROR_REPLY */
/*  Tell master channeld has sent the error message. */
u8 *towire_channeld_send_error_reply(const tal_t *ctx);
bool fromwire_channeld_send_error_reply(const void *p);

/* WIRE: CHANNELD_DEV_QUIESCE */
/*  Ask channeld to quiesce. */
u8 *towire_channeld_dev_quiesce(const tal_t *ctx);
bool fromwire_channeld_dev_quiesce(const void *p);

/* WIRE: CHANNELD_DEV_QUIESCE_REPLY */
u8 *towire_channeld_dev_quiesce_reply(const tal_t *ctx);
bool fromwire_channeld_dev_quiesce_reply(const void *p);

/* WIRE: CHANNELD_UPGRADED */
/*  Tell master we're upgrading the commitment tx. */
u8 *towire_channeld_upgraded(const tal_t *ctx, const struct channel_type *new_type);
bool fromwire_channeld_upgraded(const tal_t *ctx, const void *p, struct channel_type **new_type);

/* WIRE: CHANNELD_BLOCKHEIGHT */
/*  Tell peer about our latest and greatest blockheight. */
u8 *towire_channeld_blockheight(const tal_t *ctx, u32 blockheight);
bool fromwire_channeld_blockheight(const void *p, u32 *blockheight);

/* WIRE: CHANNELD_DEV_PEER_SHACHAIN */
/*  Tell channeld about peer's shachain seed. */
u8 *towire_channeld_dev_peer_shachain(const tal_t *ctx, const struct sha256 *seed);
bool fromwire_channeld_dev_peer_shachain(const void *p, struct sha256 *seed);


#endif /* LIGHTNING_CHANNELD_CHANNELD_WIREGEN_H */
// SHA256STAMP:239463a994bc62b05c4f4b866c5d1e22fff3479b2b5a9f1e4e9a3e6cd426d4e7
