name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Python and install embit
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r modules/embit/requirements.txt
          pip install mako

      - name: Install LLVM and Clang - Ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo ln -sfT clang++-18 /usr/bin/clang++
          sudo ln -sfT clang-18 /usr/bin/clang
        shell: bash

      - name: Install LLVM and Clang - macOS
        if: matrix.os == 'macos-14'
        run: |
          brew install llvm@18
          echo "$(brew --prefix llvm@18)/bin" >> $GITHUB_PATH
          export PATH="$(brew --prefix llvm@18)/bin:$PATH"
        shell: bash

      - name: Install Boost - Ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt install libboost-all-dev

      - name: Install Boost and build dependencies - macOS
        if: matrix.os == 'macos-14'
        run: |
          brew install boost autoconf gnu-sed automake libtool gettext pkg-config protobuf libsodium

      - name: Setup common environment - Ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          echo "CC=/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

      - name: Setup common environment - macOS
        if: matrix.os == 'macos-14'
        run: |
          export CC=$(brew --prefix llvm@18)/bin/clang
          export CXX=$(brew --prefix llvm@18)/bin/clang++
          echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV

      - name: Test - script
        timeout-minutes: 5
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_BITCOIN"
          ./auto_build.sh
          FUZZ=script ./bitcoinfuzz -runs=100

      - name: Test - deserialize_block
        timeout-minutes: 5
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD"
          ./auto_build.sh
          FUZZ=deserialize_block ./bitcoinfuzz -runs=100

      - name: Test - script_eval
        timeout-minutes: 5
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DBTCD"
          ./auto_build.sh
          FUZZ=script_eval ./bitcoinfuzz -runs=100

      - name: Test - descriptor_parse
        timeout-minutes: 5
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_MINISCRIPT"
          ./auto_build.sh
          ASAN_OPTIONS=detect_leaks=0 FUZZ=descriptor_parse ./bitcoinfuzz -runs=100

      - name: Test - miniscript_parse
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_MINISCRIPT"
          ./auto_build.sh
          ASAN_OPTIONS=detect_leaks=0 FUZZ=miniscript_parse ./bitcoinfuzz -runs=0

      - name: Test - script_asm
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DBTCD"
          ./auto_build.sh
          FUZZ=script_asm ./bitcoinfuzz -runs=0

      - name: Test - address_parse
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_BITCOIN"
          ./auto_build.sh
          FUZZ=address_parse ./bitcoinfuzz -runs=100

      - name: Test - psbt_parse
        run: |
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD"
          ./auto_build.sh
          ASAN_OPTIONS=detect_leaks=0 FUZZ=psbt_parse ./bitcoinfuzz -runs=100

      - name: Test - deserialize_invoice
        run: |
          export CXXFLAGS="-DLDK -DLND -DCLIGHTNING -DCUSTOM_MUTATOR_BOLT11"
          ./auto_build.sh
          ASAN_OPTIONS=detect_leaks=0 FUZZ=deserialize_invoice ./bitcoinfuzz -runs=100

      - name: Test - deserialize_offer
        run: |
          export CXXFLAGS="-DLDK -DCLIGHTNING"
          ./auto_build.sh
          ASAN_OPTIONS=detect_leaks=0 FUZZ=deserialize_offer ./bitcoinfuzz -runs=100
